Lang = {
  ['dispatch_name']         	= '^5 Dispatch: ',
  ['police_notify']         	= '^0Ongoing BANK ROBBERY in ^1%s^0 at ^3%s^0',
  ['silent_alarm']         	  = '^0A silent alarm has been triggered in ^3%s',
  -- Drilling Draw Texts:
  ['safe_not_drilled']        = '~r~[E]~s~ | Drill Safe',
  ['safe_drilled']            = 'Safe ~g~[drilled]~s~',
  ['safe_destroyed']          = 'Safe ~r~[destroyed]~s~',
  ['safe_reward_txt']         = 'You found ~y~%sx~s~ %s',
  -- Drilling Texts:
  ['safe_destroyed_noti']     = 'This safe is ~r~destroyed',
  ['safe_arealdy_robbed']     = 'This safe is already ~g~robbed~s~!',
  ['you_destroyed_safe']      = 'You ~r~destroyed~s~ the safe!',
  ['drilling_paused']         = 'You ~y~stopped~s~ drilling',
  ['safe_drilled_by_ply']     = 'This safe is drilled by someone else.',
  ['drill_item_usable']       = 'Your drill is still usable',
  ['drill_item_not_usable']   = 'Your drill is not usable anymore',
  -- Bank Draw Texts:
  ['hack_keypad_1']           = '~r~[E]~s~ | Hack Keypad',
  ['open_keypad_1']           = '~y~[G]~s~ | Use Access Card',
  ['hack_keypad_2']           = '~r~[K]~s~ | Hack Keypad',
  ['open_keypad_2']           = '~y~[G]~s~ | Use Access Card',
  ['lockpick_desk_door']      = '~r~[E]~s~ | Lockpick Door',
  ['open_desk_door']          = '~r~[E]~s~ | Open Door',
  ['open_desk_door_pol']      = '~r~[E]~s~ | Open Door | ~r~[G]~s~ Secure Bank',
  ['close_desk_door']         = '~r~[E]~s~ | Close Door',
  ['close_desk_door_pol']     = '~r~[E]~s~ | Close Door | ~r~[G]~s~ Secure Bank',
  ['desk_cash_not_robbed']    = '~r~[E]~s~ | Rob Petty Cash',
  ['desk_cash_robbed']        = 'Cash ~g~[robbed]~s~',
  ['power_box_not_disabled']  = '~r~[E]~s~ | Disable Electric',
  ['power_box_disabled']      = 'Power Box ~r~[disabled]~s~',
  ['open_pacific_safe']       = '~r~[E]~s~ | Open Safe',
  ['pacific_safe_cracked']    = 'Safe ~g~[cracked]~s~',
  ['close_vault_dr']          = '~g~[E]~s~ | Close Vault Door',
  ['open_vault_dr']           = '~g~[E]~s~ | Open Vault Door',
  ['open_vault_dr_pol']       = '~g~[E]~s~ Open Vault Door | ~r~[G]~s~ Secure Vault',
  -- Bank Text:
  ['bank_in_lockdown']        = 'BANK IN LOCKDOWN',
  ['no_drill']                = 'You need a drill.',
  ['no_hacking_dev']          = 'You need a hacking device!',
  ['no_access_card']          = 'You need the access card from the safe.',
  ['no_lockpick']             = 'You need a lockpick!',
  ['no_hammerwirecutter']     = 'You need a Hammer & Wire Cutter',
  ['get_closer_to_door']      = 'Move closer to the door to interact.',
  ['vault_dr_must_close']     = 'You need to close the vault door first!',
  ['found_access_card']       = 'You found an access card in the safe.',
  ['hacker_dev_corrupted']    = 'Hacker Device got corrupted, no longer usable.',
  ['you_secured_bank']        = 'You secured the bank. All banks will be unlocked!',
  ['no_access_to_cam']        = 'You do not have access to security cameras.',
  ['notify_free_time']        = 'Electric is cutted. You have ~b~%s seconds~s~ until silent alarm is triggered.',
  ['extra_free_time_added']   = 'More time added. You now have: ~b~%s seconds~s~ until silent alarm is triggered.',
  -- Camera:
  ['camera_not_exist']        = 'Entered camera ID does not exist.',

}