Config = {
  ["UsingLoader"]     = false,
  
  ["UsingESX"]        = true,
  ["UsingESX_V1.2.0"] = false,
  ["UsingKashacters"] = false,
  ["CashAccountName"] = "money",
  ["BankAccountName"] = "bank",
}

Controls = {
Focus = 185,
Grab = 24,
}

furni = {}

furni.objects = {
["Couches"] = {
  [1] = { ["object"] = "miss_rub_couch_01", ["price"] = 300, ["name"] = "Old Flowered Couch" },
  [2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 700, ["name"] = "3 Seat Chair" },
  [3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 250, ["name"] = "Old 1 Seat Couch" },
  [4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 300, ["name"] = "Old 3 Seat Couch" },
  [5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 300, ["name"] = "Old Striped Couch" },
  [6] = { ["object"] = "v_res_d_armchair", ["price"] = 300, ["name"] = "Old 1 Seat Couch Yellow" },
  [7] = { ["object"] = "v_res_fh_sofa", ["price"] = 370, ["name"] = "Corner Sofa" },
  [8] = { ["object"] = "v_res_mp_sofa", ["price"] = 370, ["name"] = "Corner Sofa 2" },
  [9] = { ["object"] = "v_res_d_sofa", ["price"] = 700, ["name"] = "Wrapped Sofa" },
  [10] = { ["object"] = "v_res_j_sofa", ["price"] = 700, ["name"] = "Old Sofa" },
  [11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 700, ["name"] = "Single Green Sofa" },
  [12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 700, ["name"] = "White Double Sofa" },
  [13] = { ["object"] = "v_res_r_sofa", ["price"] = 700, ["name"] = "Triple Cream Sofa" },
  [14] = { ["object"] = "v_res_tre_sofa", ["price"] = 700, ["name"] = "Blue Sofa" },
  [15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 700, ["name"] = "Ripped AF Blue Sofa" },
  [16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 700, ["name"] = "Blue Dirty Sofa" },
  [17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 700, ["name"] = "Blue Ripped Sofa" },
  [18] = { ["object"] = "v_res_tt_sofa", ["price"] = 700, ["name"] = "Brown Triple Chair" },
  [19] = { ["object"] = "prop_rub_couch02", ["price"] = 700, ["name"] = "Half Ripped Sofa" },
  [20] = { ["object"] = "apa_mp_h_stn_foot_stool_02", ["price"] = 250, ["name"] = "foot stool 1" },
  [21] = { ["object"] = "apa_mp_h_stn_foot_stool_01", ["price"] = 250, ["name"] = "foot stool 2" },
[22] = { ["object"] = "prop_couch_01", ["price"] = 500, ["name"] = "Double Brown Sofa" },
[23] = { ["object"] = "prop_couch_03", ["price"] = 500, ["name"] = "Triple Brown Sofa" },
[24] = { ["object"] = "prop_couch_04", ["price"] = 500, ["name"] = "Modern Brown Sofa" },
[25] = { ["object"] = "prop_couch_lg_02", ["price"] = 650, ["name"] = "Double Brown Bench" },
[26] = { ["object"] = "prop_couch_lg_05", ["price"] = 650, ["name"] = "Double Cream Sofa" },
[27] = { ["object"] = "prop_couch_lg_06", ["price"] = 650, ["name"] = "Triple Brown Sofa 2" },
[28] = { ["object"] = "prop_couch_lg_07", ["price"] = 650, ["name"] = "White Triple Sofa" },
[29] = { ["object"] = "prop_couch_lg_08", ["price"] = 650, ["name"] = "Brown Triple Sofa 2" },
  [30] = { ["object"] = "prop_couch_sm1_07", ["price"] = 370, ["name"] = "Corner Sofa 3" },
  [31] = { ["object"] = "prop_couch_sm2_07", ["price"] = 370, ["name"] = "Corner Sofa 4" },
[32] = { ["object"] = "prop_couch_sm_05", ["price"] = 850, ["name"] = "Single Cream Sofa" },
[33] = { ["object"] = "prop_couch_sm_06", ["price"] = 850, ["name"] = "Double Brown Sofa 2" },
[34] = { ["object"] = "apa_mp_h_yacht_sofa_01", ["price"] = 100, ["name"] = "Yatch Sofa" },
[35] = { ["object"] = "apa_mp_h_yacht_sofa_01", ["price"] = 100, ["name"] = "Long White Sofa" },
[36] = { ["object"] = "apa_mp_h_stn_sofacorn_01", ["price"] = 100, ["name"] = "White Corner Sofa" },
[37] = { ["object"] = "apa_mp_h_stn_sofacorn_05", ["price"] = 100, ["name"] = "Blue Corner Sofa" },
[38] = { ["object"] = "apa_mp_h_stn_sofacorn_06", ["price"] = 100, ["name"] = "Green Corner Sofa" },
[39] = { ["object"] = "apa_mp_h_stn_sofacorn_07", ["price"] = 100, ["name"] = "Dark Blue Corner Sofa" },
[40] = { ["object"] = "apa_mp_h_stn_sofacorn_08", ["price"] = 100, ["name"] = "Cream Corner Sofa" },
[41] = { ["object"] = "apa_mp_h_stn_sofacorn_10", ["price"] = 100, ["name"] = "Modern White Corner Sofa" },
[42] = { ["object"] = "bkr_prop_clubhouse_sofa_01a", ["price"] = 100, ["name"] = "Double Black Sofa" },
[43] = { ["object"] = "ex_mp_h_off_sofa_003", ["price"] = 100, ["name"] = "Triple Blue Sofa" },
[44] = { ["object"] = "ex_mp_h_off_sofa_01", ["price"] = 100, ["name"] = "White Triple Sofa" },
[45] = { ["object"] = "ex_mp_h_off_sofa_02", ["price"] = 100, ["name"] = "Black Triple Sofa" },
[46] = { ["object"] = "hei_heist_stn_sofa2seat_03", ["price"] = 100, ["name"] = "Cream Sofa" },
[47] = { ["object"] = "hei_heist_stn_sofa2seat_06", ["price"] = 100, ["name"] = "Brown Sofa" },
[48] = { ["object"] = "hei_heist_stn_sofa3seat_01", ["price"] = 100, ["name"] = "White Sofa" },
[49] = { ["object"] = "hei_heist_stn_sofa3seat_02", ["price"] = 100, ["name"] = "Triple Cream Sofa 2" },
[50] = { ["object"] = "hei_heist_stn_sofa3seat_06", ["price"] = 100, ["name"] = "Triple Gray Sofa" },
},

["Chairs"] = {
  [1] = { ["object"] = "v_res_d_highchair", ["price"] = 700, ["name"] = "High Chair" },
  [2] = { ["object"] = "v_res_fa_chair01", ["price"] = 700, ["name"] = "Chair" },
  [3] = { ["object"] = "v_res_fa_chair02", ["price"] = 700, ["name"] = "Chair" },
  [4] = { ["object"] = "v_res_fh_barcchair", ["price"] = 700, ["name"] = "High Chair" },
  [5] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 700, ["name"] = "Dine Chair 1" },
  [6] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 700, ["name"] = "Dine Chair 2" },
  [7] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 700, ["name"] = "Dine Chair 3" },
  [8] = { ["object"] = "v_res_fh_easychair", ["price"] = 700, ["name"] = "Chair" },
  [9] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 700, ["name"] = "Stool" },
  [10] = { ["object"] = "v_res_fh_singleseat", ["price"] = 700, ["name"] = "High Chair" },
  [11] = { ["object"] = "v_res_jarmchair", ["price"] = 700, ["name"] = "Arm Chair" },
  [12] = { ["object"] = "v_res_j_dinechair", ["price"] = 700, ["name"] = "Dining Chair" },
  [13] = { ["object"] = "v_res_j_stool", ["price"] = 700, ["name"] = "Stool" },
  [14] = { ["object"] = "v_res_mbchair", ["price"] = 700, ["name"] = "MB Chair" },
  [15] = { ["object"] = "v_res_m_armchair", ["price"] = 700, ["name"] = "Arm Chair" },
  [16] = { ["object"] = "v_res_m_dinechair", ["price"] = 700, ["name"] = "Dine Chair" },
  [17] = { ["object"] = "v_res_study_chair", ["price"] = 700, ["name"] = "Study Chair" },
  [18] = { ["object"] = "v_res_trev_framechair", ["price"] = 700, ["name"] = "Frame Chair" },
  [19] = { ["object"] = "v_res_tre_chair", ["price"] = 700, ["name"] = "Chair" },
  [20] = { ["object"] = "v_res_tre_officechair", ["price"] = 700, ["name"] = "Office Chair" },
  [21] = { ["object"] = "v_res_tre_stool", ["price"] = 700, ["name"] = "Stool" },
  [22] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 700, ["name"] = "Stool Leather" },
  [23] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 700, ["name"] = "Stool Scuz" },
  [24] = { ["object"] = "v_med_p_deskchair", ["price"] = 700, ["name"] = "Desk Chair" },
  [25] = { ["object"] = "v_med_p_easychair", ["price"] = 700, ["name"] = "Easy Chair" },
  [26] = { ["object"] = "v_med_whickerchair1", ["price"] = 700, ["name"] = "Whicker Chair" },
  [27] = { ["object"] = "prop_direct_chair_01", ["price"] = 700, ["name"] = "Direct Chair 1" },
  [28] = { ["object"] = "prop_direct_chair_02", ["price"] = 700, ["name"] = "Direct Chair 2" },
  [29] = { ["object"] = "prop_yacht_lounger", ["price"] = 700, ["name"] = "Yacht Seat 1" },
  [30] = { ["object"] = "prop_yacht_seat_01", ["price"] = 700, ["name"] = "Yacht Seat 2" },
  [31] = { ["object"] = "prop_yacht_seat_02", ["price"] = 700, ["name"] = "Yacht Seat 3" },
  [32] = { ["object"] = "prop_yacht_seat_03", ["price"] = 700, ["name"] = "Yacht Seat 4" },
  [33] = { ["object"] = "v_ret_chair_white", ["price"] = 100, ["name"] = "White Chair" },
  [34] = { ["object"] = "v_ret_chair", ["price"] = 100, ["name"] = "Chair" },
  [35] = { ["object"] = "v_ret_ta_stool", ["price"] = 100, ["name"] = "TA Stool" },
  [36] = { ["object"] = "prop_cs_office_chair", ["price"] = 100, ["name"] = "Office Chair" },
  [37] = { ["object"] = "apa_mp_h_stn_chairarm_01", ["price"] = 300, ["name"] = "Armchair 1" },
  [38] = { ["object"] = "apa_mp_h_stn_chairarm_02", ["price"] = 300, ["name"] = "Armchair 2" },
  [39] = { ["object"] = "apa_mp_h_stn_chairarm_03", ["price"] = 300, ["name"] = "Armchair 3" },
  [40] = { ["object"] = "apa_mp_h_stn_chairarm_09", ["price"] = 300, ["name"] = "Armchair 4" },
  [41] = { ["object"] = "apa_mp_h_stn_chairarm_11", ["price"] = 300, ["name"] = "Armchair 5" },
  [42] = { ["object"] = "apa_mp_h_stn_chairarm_12", ["price"] = 300, ["name"] = "Armchair 6" },
  [43] = { ["object"] = "apa_mp_h_stn_chairarm_13", ["price"] = 300, ["name"] = "Armchair 7" },
  [44] = { ["object"] = "apa_mp_h_stn_chairarm_23", ["price"] = 300, ["name"] = "Armchair 8" },
  [45] = { ["object"] = "apa_mp_h_stn_chairarm_24", ["price"] = 300, ["name"] = "Armchair 9" },
  [46] = { ["object"] = "apa_mp_h_stn_chairarm_25", ["price"] = 300, ["name"] = "Armchair 10" },
  [47] = { ["object"] = "apa_mp_h_stn_chairarm_26", ["price"] = 300, ["name"] = "Armchair 11" },
  [48] = { ["object"] = "apa_mp_h_stn_chairstrip_01", ["price"] = 300, ["name"] = "Armchair 12" },
  [49] = { ["object"] = "apa_mp_h_stn_chairstrip_02", ["price"] = 300, ["name"] = "Armchair 13" },
  [50] = { ["object"] = "apa_mp_h_stn_chairstrip_03", ["price"] = 300, ["name"] = "Armchair 14" },
  [51] = { ["object"] = "apa_mp_h_stn_chairstrip_04", ["price"] = 300, ["name"] = "Armchair 15" },
  [52] = { ["object"] = "apa_mp_h_stn_chairstrip_05", ["price"] = 300, ["name"] = "Armchair 16" },
  [53] = { ["object"] = "apa_mp_h_stn_chairstrip_06", ["price"] = 300, ["name"] = "Armchair 17" },
  [54] = { ["object"] = "apa_mp_h_stn_chairstrip_07", ["price"] = 300, ["name"] = "Armchair 18" },
  [55] = { ["object"] = "apa_mp_h_stn_chairstrip_08", ["price"] = 300, ["name"] = "Armchair 19" },
[56] = { ["object"] = "apa_mp_h_yacht_armchair_01", ["price"] = 300, ["name"] = "Armchair 20" },
[57] = { ["object"] = "apa_mp_h_yacht_armchair_03", ["price"] = 300, ["name"] = "Armchair 21" },
[58] = { ["object"] = "apa_mp_h_yacht_armchair_04", ["price"] = 300, ["name"] = "Armchair 22" },
[59] = { ["object"] = "ba_prop_battle_club_chair_01", ["price"] = 300, ["name"] = "Armchair 23" },
[60] = { ["object"] = "ba_prop_battle_club_chair_02", ["price"] = 300, ["name"] = "Armchair 24" },
[61] = { ["object"] = "ba_prop_battle_club_chair_03", ["price"] = 300, ["name"] = "Armchair 25" },
[62] = { ["object"] = "bkr_prop_clubhouse_armchair_01a", ["price"] = 300, ["name"] = "Armchair 26" },
[63] = { ["object"] = "bkr_prop_clubhouse_chair_03", ["price"] = 100, ["name"] = "Plastic Chair" },
[64] = { ["object"] = "ch_prop_casino_chair_01a", ["price"] = 100, ["name"] = "Casino Chair" },
[65] = { ["object"] = "hei_heist_din_chair_02", ["price"] = 100, ["name"] = "Armchair 27" },
[66] = { ["object"] = "hei_heist_stn_chairarm_06", ["price"] = 100, ["name"] = "Armchair 28" },
},

["Beds"] = {
  [1] = { ["object"] = "v_res_d_bed", ["price"] = 700, ["name"] = "D Bed" },  
  [2] = { ["object"] = "v_res_lestersbed", ["price"] = 700, ["name"] = "L Bed" }, 
  [3] = { ["object"] = "v_res_mbbed", ["price"] = 700, ["name"] = "MB Bed" }, 
  [4] = { ["object"] = "v_res_mdbed", ["price"] = 700, ["name"] = "MD Bed" }, 
  [5] = { ["object"] = "v_res_msonbed", ["price"] = 700, ["name"] = "Mason Bed" },  
  [6] = { ["object"] = "v_res_tre_bed1", ["price"] = 700, ["name"] = "T Bed" }, 
  [7] = { ["object"] = "v_res_tre_bed2", ["price"] = 700, ["name"] = "T Bed 2" }, 
  [8] = { ["object"] = "v_res_tt_bed", ["price"] = 700, ["name"] = "TT Bed" },
  [9] = { ["object"] = "apa_mp_h_bed_double_08", ["price"] = 700, ["name"] = "Double Bed" },  
  [10] = { ["object"] = "apa_mp_h_bed_double_09", ["price"] = 700, ["name"] = "Double Bed 2" },
  [11] = { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 700, ["name"] = "Double Bed 3" },
  [12] = { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 1000, ["name"] = "Bed with table" },
  [13] = { ["object"] = "gr_prop_bunker_bed_01", ["price"] = 500, ["name"] = "Single bed" },
  [14] = { ["object"] = "apa_mp_h_stn_sofa_daybed_01", ["price"] = 700, ["name"] = "Sofa Bed 1" },
  [15] = { ["object"] = "apa_mp_h_stn_sofa_daybed_02", ["price"] = 700, ["name"] = "Sofa Bed 2" },
  [16] = { ["object"] = "apa_mp_h_yacht_bed_01", ["price"] = 700, ["name"] = "Yatch Bed 1" },
  [17] = { ["object"] = "apa_mp_h_yacht_bed_02", ["price"] = 700, ["name"] = "Yatch Bed 2" },
  [18] = { ["object"] = "imp_prop_impexp_sofabed_01a", ["price"] = 700, ["name"] = "Sofa Bed" },
  [19] = { ["object"] = "p_mbbed_s", ["price"] = 700, ["name"] = "Double Bed 4" },

},

["General #1"] = {
  [1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 100, ["name"] = "Bean Bag 1" },
  [2] = { ["object"] = "v_res_cherubvase", ["price"] = 2500, ["name"] = "White Vase" },
  [3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 300, ["name"] = "Padded Wall" },
  [4] = { ["object"] = "v_res_d_ramskull", ["price"] = 300, ["name"] = "Item" },
  [5] = { ["object"] = "v_res_d_whips", ["price"] = 300, ["name"] = "Whips" },
  [6] = { ["object"] = "v_res_fashmag1", ["price"] = 300, ["name"] = "Mags" },
  [7] = { ["object"] = "v_res_fashmagopen", ["price"] = 300, ["name"] = "Mags Open" },
  [8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 300, ["name"] = "Mag Tidy" },
  [9] = { ["object"] = "v_res_fa_yogamat002", ["price"] = 300, ["name"] = "Yoga Mat 1" },
  [10] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 300, ["name"] = "Yoga Mat 2" },
  [11] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 300, ["name"] = "Aftershave" },
  [12] = { ["object"] = "v_res_fh_flowersa", ["price"] = 300, ["name"] = "Flowers" },
  [13] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 300, ["name"] = "Fruitbowl" },
  [14] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 300, ["name"] = "Laundry Basket" },
  [15] = { ["object"] = "v_res_fh_pouf", ["price"] = 300, ["name"] = "Pouf" },
  [16] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 300, ["name"] = "Sculpture" },
  [17] = { ["object"] = "v_res_j_magrack", ["price"] = 300, ["name"] = "Mag Rack" },
  [18] = { ["object"] = "v_res_jewelbox", ["price"] = 300, ["name"] = "Jewel Box" },
  [19] = { ["object"] = "v_res_mbbin", ["price"] = 300, ["name"] = "Bin" },
  [20] = { ["object"] = "v_res_mbowlornate", ["price"] = 300, ["name"] = "Ornate Bowl" },
  [21] = { ["object"] = "v_res_mbronzvase", ["price"] = 300, ["name"] = "Bronze Vase" },
  [22] = { ["object"] = "v_res_mchalkbrd", ["price"] = 300, ["name"] = "Chalk Board" },
  [23] = { ["object"] = "v_res_mddresser", ["price"] = 300, ["name"] = "Dresser" },
  [24] = { ["object"] = "v_res_mplinth", ["price"] = 300, ["name"] = "Linth" },
  [25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 300, ["name"] = "Ashtray" },
  [26] = { ["object"] = "v_res_m_kscales", ["price"] = 300, ["name"] = "Scales" },
  [27] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 300, ["name"] = "Bed Pillow" },
  [28] = { ["object"] = "apa_p_h_acc_artwallm_04", ["price"] = 300, ["name"] = "Wall Art 1" },
  [29] = { ["object"] = "apa_p_h_acc_artwallm_03", ["price"] = 300, ["name"] = "Wall Art 2" },
  [30] = { ["object"] = "apa_p_h_acc_artwallm_01", ["price"] = 300, ["name"] = "Wall Art 3" },
  [31] = { ["object"] = "apa_p_h_acc_artwalll_04", ["price"] = 300, ["name"] = "Wall Art 4" },
  [32] = { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 300, ["name"] = "Wall Art 5" },
  [33] = { ["object"] = "hei_heist_str_sideboardl_05", ["price"] = 100, ["name"] = "Fuckeye Object"},
  [34] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 300, ["name"] = "Rug 1" },
  [35] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 300, ["name"] = "Rug 2" },
  [36] = { ["object"] = "apa_mp_h_acc_rugwools_03", ["price"] = 300, ["name"] = "Rug 3" },
  [37] = { ["object"] = "apa_mp_h_acc_rugwooll_04", ["price"] = 300, ["name"] = "Rug 4" },
  [38] = { ["object"] = "apa_mp_h_acc_rugwoolm_01", ["price"] = 300, ["name"] = "Rug 5" },
  [39] = { ["object"] = "apa_mp_h_acc_rugwoolm_02", ["price"] = 300, ["name"] = "Rug 6" },
  [40] = { ["object"] = "apa_mp_h_acc_rugwoolm_03", ["price"] = 300, ["name"] = "Rug 7" },
  [41] = { ["object"] = "apa_mp_h_acc_rugwools_01", ["price"] = 300, ["name"] = "Rug 8" },
[42] = { ["object"] = "apa_p_h_acc_artwalll_01", ["price"] = 300, ["name"] = "Wall Art 6" },
  [43] = { ["object"] = "apa_p_h_acc_artwalll_02", ["price"] = 300, ["name"] = "Wall Art 7" },	
  [44] = { ["object"] = "hei_heist_acc_artgolddisc_01", ["price"] = 3000, ["name"] = "Gold Disc 1" },	
  [45] = { ["object"] = "hei_heist_acc_artgolddisc_02", ["price"] = 3000, ["name"] = "Gold Disc 2" },	
  [46] = { ["object"] = "hei_heist_acc_artgolddisc_03", ["price"] = 3000, ["name"] = "Gold Disc 3" },	
  [47] = { ["object"] = "hei_heist_acc_artgolddisc_04", ["price"] = 3000, ["name"] = "Gold Disc 4" },	
  [48] = { ["object"] = "vw_prop_casino_art_vase_02a", ["price"] = 3000, ["name"] = "Vase 1" },
  [49] = { ["object"] = "vw_prop_casino_art_vase_04a", ["price"] = 3000, ["name"] = "Vase 2" },
  [50] = { ["object"] = "vw_prop_casino_art_vase_10a", ["price"] = 3000, ["name"] = "Vase 3" },
  [51] = { ["object"] = "vw_prop_casino_art_vase_12a", ["price"] = 3000, ["name"] = "Vase 4" },
  [52] = { ["object"] = "vw_prop_casino_art_v_01a", ["price"] = 1000, ["name"] = "Art V 1" },
  [53] = { ["object"] = "vw_prop_casino_art_v_01b", ["price"] = 1000, ["name"] = "Art V 2" },
  [54] = { ["object"] = "vw_prop_casino_cards_01", ["price"] = 300, ["name"] = "Casino Cards" },
  [55] = { ["object"] = "vw_prop_casino_shopping_bag_01a", ["price"] = 100, ["name"] = "Casino Shopping Bag" },
  [56] = { ["object"] = "vw_prop_casino_wine_glass_01b", ["price"] = 100, ["name"] = "Wine Glass" },
  [57] = { ["object"] = "prop_watercooler_dark", ["price"] = 1000, ["name"] = "Water Cooler" },
  [58] = { ["object"] = "ba_prop_battle_trophy_dancer", ["price"] = 100, ["name"] = "Dancer Trophy" },
  [59] = { ["object"] = "v_res_desktidy", ["price"] = 100, ["name"] = "Desk Tidy" },
  [60] = { ["object"] = "prop_bar_shots", ["price"] = 100, ["name"] = "Bar Shots" },
  [61] = { ["object"] = "prop_bar_fruit", ["price"] = 100, ["name"] = "Bar Fruit" },
  [62] = { ["object"] = "prop_bar_lemons", ["price"] = 100, ["name"] = "Bar Lemons" },
  [63] = { ["object"] = "clube_ringue", ["price"] = 50000, ["name"] = "Boxing Ring" },
},

["General #2"] = {
  [1] = { ["object"] = "prop_a4_pile_01", ["price"] = 100, ["name"] = "A4 Pile" },
  [2] = { ["object"] = "prop_amb_40oz_03", ["price"] = 100, ["name"] = "40 oz" },
  [3] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 100, ["name"] = "Beer" },
  [4] = { ["object"] = "prop_aviators_01", ["price"] = 100, ["name"] = "Aviators" },
  [5] = { ["object"] = "prop_barry_table_detail", ["price"] = 100, ["name"] = "Detail" },
  [6] = { ["object"] = "prop_beer_box_01", ["price"] = 100, ["name"] = "Beers" },
  [7] = { ["object"] = "prop_binoc_01", ["price"] = 100, ["name"] = "Binoculars" },
  [8] = { ["object"] = "prop_blox_spray", ["price"] = 100, ["name"] = "Blox Spray" },
  [9] = { ["object"] = "prop_bongos_01", ["price"] = 100, ["name"] = "Bongos" },
  [10] = { ["object"] = "prop_bong_01", ["price"] = 100, ["name"] = "Bong" },
  [11] = { ["object"] = "prop_boombox_01", ["price"] = 100, ["name"] = "Boombox" },
  [12] = { ["object"] = "prop_bowl_crisps", ["price"] = 100, ["name"] = "Bowl Crisps" },
  [13] = { ["object"] = "prop_candy_pqs", ["price"] = 100, ["name"] = "Candy" },
  [14] = { ["object"] = "prop_carrier_bag_01", ["price"] = 100, ["name"] = "Carrier bag" },
  [15] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 100, ["name"] = "Ceramic Jug" },
  [16] = { ["object"] = "prop_cigar_pack_01", ["price"] = 100, ["name"] = "Cigar Pack 1" },
  [17] = { ["object"] = "prop_cigar_pack_02", ["price"] = 100, ["name"] = "Cigar Pack 2" },
  [18] = { ["object"] = "prop_cs_beer_box", ["price"] = 100, ["name"] = "Beer Box 2" },
  [19] = { ["object"] = "prop_cs_binder_01", ["price"] = 100, ["name"] = "Binder" },
  [20] = { ["object"] = "prop_cs_bs_cup", ["price"] = 100, ["name"] = "Cup" },
  [21] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 100, ["name"] = "Envelope" },
  [22] = { ["object"] = "prop_cs_champ_flute", ["price"] = 100, ["name"] = "Flute" },
  [23] = { ["object"] = "prop_cs_duffel_01", ["price"] = 100, ["name"] = "Duffel Bag" },
  [24] = { ["object"] = "prop_cs_dvd", ["price"] = 50, ["name"] = "DVD" },
  [25] = { ["object"] = "prop_cs_dvd_case", ["price"] = 50, ["name"] = "DVD Case" },
  [26] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 100, ["name"] = "Film Reel" },
  [27] = { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 100, ["name"] = "Blind" },
  [28] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 100, ["name"] = "Bag" },
  [29] = { ["object"] = "prop_cs_ironing_board", ["price"] = 100, ["name"] = "Ironing Board" },
  [30] = { ["object"] = "prop_cs_katana_01", ["price"] = 100, ["name"] = "Katana" },
  [31] = { ["object"] = "prop_cs_kettle_01", ["price"] = 100, ["name"] = "Kettle" },
  [32] = { ["object"] = "prop_cs_lester_crate", ["price"] = 100, ["name"] = "Crate" },
  [33] = { ["object"] = "prop_cs_petrol_can", ["price"] = 100, ["name"] = "Petrol Can" },
  [34] = { ["object"] = "prop_cs_sack_01", ["price"] = 100, ["name"] = "Sack" },
  [35] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 100, ["name"] = "Script Bottle" },
  [36] = { ["object"] = "prop_cs_script_bottle", ["price"] = 100, ["name"] = "Script Bottle 2" },
  [37] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 100, ["name"] = "Bin Bag" },
  [38] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 100, ["name"] = "Whiskey Bottle" },
  [39] = { ["object"] = "prop_sh_bong_01", ["price"] = 100, ["name"] = "Bong" },
  [40] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 100, ["name"] = "Peanuts" },
  [41] = { ["object"] = "prop_tumbler_01", ["price"] = 100, ["name"] = "Tumbler" },
  [42] = { ["object"] = "nomy_piano", ["price"] = 4000, ["name"] = "Grand Piano" },
  [43] = { ["object"] = "prop_tool_adjspanner", ["price"] = 400, ["name"] = "Adj Spanner" },
  [44] = { ["object"] = "prop_bottle_brandy", ["price"] = 400, ["name"] = "Brandy Bottle" },
  [45] = { ["object"] = "prop_bottle_cognac", ["price"] = 400, ["name"] = "Cognac Bottle" },
  [46] = { ["object"] = "prop_bottle_macbeth", ["price"] = 400, ["name"] = "Macbeth Bottle" },
  [47] = { ["object"] = "prop_bottle_richard", ["price"] = 400, ["name"] = "Richard Bottle" },
  [48] = { ["object"] = "prop_rum_bottle", ["price"] = 400, ["name"] = "Rum Bottle" },
  [49] = { ["object"] = "xs_prop_arena_champ_closed", ["price"] = 100, ["name"] = "Champ Bottle" },
  [50] = { ["object"] = "prop_fountain1", ["price"] = 4000, ["name"] = "Fountain 1" },
  [51] = { ["object"] = "prop_fountain2", ["price"] = 4000, ["name"] = "Fountain 2" },
  [52] = { ["object"] = "prop_cs_book_01", ["price"] = 100, ["name"] = "Book 1" },
  [53] = { ["object"] = "prop_cs_stock_book", ["price"] = 100, ["name"] = "Book 2" },
  [54] = { ["object"] = "vw_prop_book_stack_01a", ["price"] = 100, ["name"] = "Book 3" },
  [55] = { ["object"] = "vw_prop_book_stack_01b", ["price"] = 100, ["name"] = "Book 4" },
  [56] = { ["object"] = "vw_prop_book_stack_01c", ["price"] = 100, ["name"] = "Book 5" },
  [57] = { ["object"] = "vw_prop_book_stack_02a", ["price"] = 100, ["name"] = "Book 6" },
  [58] = { ["object"] = "vw_prop_book_stack_02b", ["price"] = 100, ["name"] = "Book 7" },
  [59] = { ["object"] = "vw_prop_book_stack_02c", ["price"] = 100, ["name"] = "Book 8" },
  [60] = { ["object"] = "vw_prop_book_stack_03a", ["price"] = 100, ["name"] = "Book 9" },
  [61] = { ["object"] = "vw_prop_book_stack_03b", ["price"] = 100, ["name"] = "Book 10" },
  [62] = { ["object"] = "vw_prop_book_stack_03c", ["price"] = 100, ["name"] = "Book 11" },
  [63] = { ["object"] = "vw_prop_notebook_01a", ["price"] = 100, ["name"] = "NoteBook" },
  [64] = { ["object"] = "v_ilev_mp_bedsidebook", ["price"] = 100, ["name"] = "Beside Book" },
  [65] = { ["object"] = "vw_prop_casino_art_mod_06a", ["price"] = 1000, ["name"] = "Mod Art 1" },
  [66] = { ["object"] = "vw_prop_casino_art_bowling_01a", ["price"] = 1000, ["name"] = "Bowling Art 1" },
  [67] = { ["object"] = "vw_prop_casino_art_bowling_01b", ["price"] = 1000, ["name"] = "Bowling Art 2" },
  [68] = { ["object"] = "vw_prop_casino_art_car_01a", ["price"] = 1000, ["name"] = "Car Art 1" },
  [69] = { ["object"] = "vw_prop_casino_art_car_02a", ["price"] = 1000, ["name"] = "Car Art 2" },
  [70] = { ["object"] = "vw_prop_casino_art_car_03a", ["price"] = 1000, ["name"] = "Car Art 3" },
  [71] = { ["object"] = "vw_prop_casino_art_car_04a", ["price"] = 1000, ["name"] = "Car Art 4" },
  [72] = { ["object"] = "vw_prop_casino_art_car_05a", ["price"] = 1000, ["name"] = "Car Art 5" },
  [73] = { ["object"] = "vw_prop_casino_art_car_06a", ["price"] = 1000, ["name"] = "Car Art 6" },
  [74] = { ["object"] = "vw_prop_casino_art_car_07a", ["price"] = 1000, ["name"] = "Car Art 7" },
  [75] = { ["object"] = "vw_prop_casino_art_car_08a", ["price"] = 1000, ["name"] = "Car Art 8" },
  [76] = { ["object"] = "vw_prop_casino_art_car_09a", ["price"] = 1000, ["name"] = "Car Art 9" },
  [77] = { ["object"] = "vw_prop_casino_art_car_10a", ["price"] = 1000, ["name"] = "Car Art 10" },
  [78] = { ["object"] = "vw_prop_casino_art_car_11a", ["price"] = 1000, ["name"] = "Car Art 11" },
  [79] = { ["object"] = "vw_prop_casino_art_car_12a", ["price"] = 1000, ["name"] = "Car Art 12" },
  [80] = { ["object"] = "vw_prop_casino_art_cherries_01a", ["price"] = 1000, ["name"] = "Cherries Art 1" },
  [81] = { ["object"] = "vw_prop_casino_art_concrete_01a", ["price"] = 1000, ["name"] = "Concrete Art 1" },
  [82] = { ["object"] = "vw_prop_casino_art_concrete_02a", ["price"] = 1000, ["name"] = "Concrete Art 2" },
  [83] = { ["object"] = "vw_prop_casino_art_console_02a", ["price"] = 1000, ["name"] = "Console Art 1" },
  [84] = { ["object"] = "vw_prop_casino_art_console_01a", ["price"] = 1000, ["name"] = "Console Art 2" },
  [85] = { ["object"] = "vw_prop_casino_art_deer_01a", ["price"] = 1000, ["name"] = "Deer Art" },
  [86] = { ["object"] = "vw_prop_casino_art_dog_01a", ["price"] = 1000, ["name"] = "Dog Art" },
  [87] = { ["object"] = "vw_prop_casino_art_egg_01a", ["price"] = 1000, ["name"] = "Egg Art" },
  [88] = { ["object"] = "vw_prop_casino_art_ego_01a", ["price"] = 1000, ["name"] = "Ego Art" },
  [89] = { ["object"] = "vw_prop_casino_art_grenade_01a", ["price"] = 1000, ["name"] = "Grenade Art 1" },
  [90] = { ["object"] = "vw_prop_casino_art_grenade_01d", ["price"] = 1000, ["name"] = "Grenade Art 2" },
  [91] = { ["object"] = "vw_prop_casino_art_grenade_01c", ["price"] = 1000, ["name"] = "Grenade Art 3" },
  [92] = { ["object"] = "vw_prop_casino_art_guitar_01a", ["price"] = 1000, ["name"] = "Guitar Art 1" },
  [93] = { ["object"] = "vw_prop_casino_art_head_01a", ["price"] = 1000, ["name"] = "Head Art 1" },
  [94] = { ["object"] = "vw_prop_casino_art_head_01b", ["price"] = 1000, ["name"] = "Head Art 2" },
  [95] = { ["object"] = "vw_prop_casino_art_head_01c", ["price"] = 1000, ["name"] = "Head Art 3" },
  [96] = { ["object"] = "vw_prop_casino_art_head_01d", ["price"] = 1000, ["name"] = "Head Art 4" },
  [97] = { ["object"] = "vw_prop_casino_art_horse_01a", ["price"] = 1000, ["name"] = "Horse Art 1" },
  [98] = { ["object"] = "vw_prop_casino_art_horse_01b", ["price"] = 1000, ["name"] = "Horse Art 2" },
  [99] = { ["object"] = "vw_prop_casino_art_horse_01c", ["price"] = 1000, ["name"] = "Horse Art 3" },
  [100] = { ["object"] = "vw_prop_casino_art_lollipop_01a", ["price"] = 1000, ["name"] = "Lollipop Art" },
  [101] = { ["object"] = "vw_prop_casino_art_miniature_05a", ["price"] = 1000, ["name"] = "Miniature Art 1" },
  [102] = { ["object"] = "vw_prop_casino_art_miniature_05b", ["price"] = 1000, ["name"] = "Miniature Art 2" },
  [103] = { ["object"] = "vw_prop_casino_art_miniature_05c", ["price"] = 1000, ["name"] = "Miniature Art 3" },
  [104] = { ["object"] = "vw_prop_casino_art_miniature_09a", ["price"] = 1000, ["name"] = "Miniature Art 4" },
  [105] = { ["object"] = "vw_prop_casino_art_miniature_09b", ["price"] = 1000, ["name"] = "Miniature Art 5" },
  [106] = { ["object"] = "vw_prop_casino_art_miniature_09c", ["price"] = 1000, ["name"] = "Miniature Art 6" },
  [107] = { ["object"] = "vw_prop_miniature_yacht_01a", ["price"] = 1000, ["name"] = "Yatch Miniature 1" },
  [108] = { ["object"] = "vw_prop_miniature_yacht_01b", ["price"] = 1000, ["name"] = "Yatch Miniature 2" },
  [109] = { ["object"] = "vw_prop_miniature_yacht_01c", ["price"] = 1000, ["name"] = "Yatch Miniature 3" },
  [110] = { ["object"] = "vw_prop_casino_art_panther_01a", ["price"] = 1000, ["name"] = "Panther Art 1" },
  [111] = { ["object"] = "vw_prop_casino_art_panther_01b", ["price"] = 1000, ["name"] = "Panther Art 2" },
  [112] = { ["object"] = "vw_prop_casino_art_panther_01c", ["price"] = 1000, ["name"] = "Panther Art 3" },
  [113] = { ["object"] = "vw_prop_casino_art_sculpture_02a", ["price"] = 1000, ["name"] = "Sculpture Art 1" },
  [114] = { ["object"] = "vw_prop_casino_art_sculpture_02b", ["price"] = 1000, ["name"] = "Sculpture Art 2" },
  [115] = { ["object"] = "vw_prop_casino_art_statue_01a", ["price"] = 1000, ["name"] = "Statue 1" },
  [116] = { ["object"] = "vw_prop_casino_art_statue_02a", ["price"] = 1000, ["name"] = "Statue 2" },
  [117] = { ["object"] = "vw_prop_casino_art_statue_04a", ["price"] = 1000, ["name"] = "Statue 3" },
  [118] = { ["object"] = "ba_prop_battle_champ_open", ["price"] = 100, ["name"] = "Champ Bottle Open" },


},

["General #3"] = {
  [1] = { ["object"] = "v_ret_csr_bin", ["price"] = 100, ["name"] = "CSR Bin" },
  [2] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 100, ["name"] = "Basket" },
  [3] = { ["object"] = "v_ret_gc_bag01", ["price"] = 100, ["name"] = "GC Bag 1" },
  [4] = { ["object"] = "v_ret_gc_bag02", ["price"] = 100, ["name"] = "GC Bag 2" },
  [5] = { ["object"] = "v_ret_gc_bin", ["price"] = 100, ["name"] = "GC Bin" },
  [6] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 100, ["name"] = "Cash Register" },
  [7] = { ["object"] = "v_ret_gc_chair01", ["price"] = 100, ["name"] = "GC Chair 01" },
  [8] = { ["object"] = "v_ret_gc_chair02", ["price"] = 100, ["name"] = "GC Chair 02" },
  [9] = { ["object"] = "v_ret_gc_clock", ["price"] = 100, ["name"] = "Clock" },
  [10] = { ["object"] = "v_ret_hd_prod1_", ["price"] = 100, ["name"] = "Prod 1" },
  [11] = { ["object"] = "v_ret_hd_prod2_", ["price"] = 100, ["name"] = "Prod 2" },
  [12] = { ["object"] = "v_ret_hd_prod3_", ["price"] = 100, ["name"] = "Prod 3" },
  [13] = { ["object"] = "v_ret_hd_prod4_", ["price"] = 100, ["name"] = "Prod 4" },
  [14] = { ["object"] = "v_ret_hd_prod5_", ["price"] = 100, ["name"] = "Prod 5" },
  [15] = { ["object"] = "v_ret_hd_prod6_", ["price"] = 100, ["name"] = "Prod 6" },
  [16] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 100, ["name"] = "HD Unit 1" },
  [17] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 100, ["name"] = "HD Unit 2" },
  [18] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 100, ["name"] = "Fridge" },
  [19] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 100, ["name"] = "Bag 1" },
  [20] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 100, ["name"] = "Bag 2" },
  [21] = { ["object"] = "v_ret_ta_book1", ["price"] = 100, ["name"] = "Book 1" },
  [22] = { ["object"] = "v_ret_ta_book2", ["price"] = 100, ["name"] = "Book 2" },
  [23] = { ["object"] = "v_ret_ta_book3", ["price"] = 100, ["name"] = "Book 3" },
  [24] = { ["object"] = "v_ret_ta_book4", ["price"] = 100, ["name"] = "Book 4" },
  [25] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 100, ["name"] = "First Aid" },
  [26] = { ["object"] = "v_ret_ta_hero", ["price"] = 100, ["name"] = "Hero" },
  [27] = { ["object"] = "v_ret_ta_mag1", ["price"] = 100, ["name"] = "Mag 1" },
  [28] = { ["object"] = "v_ret_ta_mag2", ["price"] = 100, ["name"] = "Mag 2" },
  [29] = { ["object"] = "v_ret_ta_skull", ["price"] = 100, ["name"] = "Skull" },
  [30] = { ["object"] = "prop_acc_guitar_01", ["price"] = 100, ["name"] = "Guitar" },
  [31] = { ["object"] = "prop_amb_handbag_01", ["price"] = 100, ["name"] = "Handbag" },
  [32] = { ["object"] = "prop_attache_case_01", ["price"] = 100, ["name"] = "Case" },
  [33] = { ["object"] = "prop_big_bag_01", ["price"] = 100, ["name"] = "Big Bag" },
  [34] = { ["object"] = "prop_bonesaw", ["price"] = 100, ["name"] = "Bonesaw" },
  [35] = { ["object"] = "prop_cs_fertilizer", ["price"] = 100, ["name"] = "Fertilizer" },
  [36] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 100, ["name"] = "Shopping Bag" },
  [37] = { ["object"] = "prop_cs_vial_01", ["price"] = 100, ["name"] = "Vial" },
  [38] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 100, ["name"] = "Ragdoll" }, 
  [39] = { ["object"] = "prop_t_telescope_01b", ["price"] = 1000, ["name"] = "Telescope" }, 
  [40] = { ["object"] = "prop_table_ten_bat", ["price"] = 1000, ["name"] = "Tennis bat" },
  [41] = { ["object"] = "apa_mp_h_acc_candles_01", ["price"] = 300, ["name"] = "Candle 1" },
[42] = { ["object"] = "v_res_m_candle", ["price"] = 300, ["name"] = "Candle 2" },
  [43] = { ["object"] = "v_res_m_candlelrg", ["price"] = 300, ["name"] = "Candle 3" },
  [44] = { ["object"] = "apa_mp_h_acc_candles_02", ["price"] = 300, ["name"] = "Candle 4" },
  [45] = { ["object"] = "apa_mp_h_acc_candles_04", ["price"] = 300, ["name"] = "Candle 5" },
  [46] = { ["object"] = "apa_mp_h_acc_candles_05", ["price"] = 300, ["name"] = "Candle 6" },
  [47] = { ["object"] = "apa_mp_h_acc_candles_06", ["price"] = 300, ["name"] = "Candle 7" },
  [48] = { ["object"] = "prop_mem_candle_01", ["price"] = 300, ["name"] = "Candle 8" },
  [49] = { ["object"] = "prop_mem_candle_02", ["price"] = 300, ["name"] = "Candle 9" },
  [50] = { ["object"] = "prop_mem_candle_03", ["price"] = 300, ["name"] = "Candle 10" },
  [51] = { ["object"] = "prop_mem_candle_04", ["price"] = 300, ["name"] = "Candle 11" },
  [52] = { ["object"] = "prop_mem_candle_05", ["price"] = 300, ["name"] = "Candle 12" },
  [53] = { ["object"] = "prop_mem_candle_06", ["price"] = 300, ["name"] = "Candle 13" },
  [54] = { ["object"] = "prop_mem_candle_combo", ["price"] = 300, ["name"] = "Candle Combo" },
  [55] = { ["object"] = "v_prop_floatcandle", ["price"] = 300, ["name"] = "Float Candle" },
  [56] = { ["object"] = "ch_prop_ch_trophy_gunner_01a", ["price"] = 300, ["name"] = "Gunner Trophy 1" },
  [57] = { ["object"] = "vw_prop_casino_art_gun_01a", ["price"] = 300, ["name"] = "Gunner Trophy 2" },
  [58] = { ["object"] = "vw_prop_casino_art_gun_02a", ["price"] = 300, ["name"] = "Gunner Trophy 3" },
  [59] = { ["object"] = "xm_int_prop_tinsel_truck_gunmod", ["price"] = 300, ["name"] = "Tinsel 1" },
  [60] = { ["object"] = "xm_int_prop_tinsel_truck_carmod", ["price"] = 300, ["name"] = "Tinsel 2" },
  [61] = { ["object"] = "prop_beer_neon_03", ["price"] = 300, ["name"] = "Bear Neon" },
  [62] = { ["object"] = "ch_prop_podium_casino_01a", ["price"] = 1000, ["name"] = "Casino Podium" },
},

["General #4"] = {
  [1] = { ["object"] = "prop_dummy_01", ["price"] = 100, ["name"] = "Dummy" },
  [2] = { ["object"] = "prop_egg_clock_01", ["price"] = 100, ["name"] = "Egg Clock" },
  [3] = { ["object"] = "prop_el_guitar_01", ["price"] = 100, ["name"] = "E Guitar 1" },
  [4] = { ["object"] = "prop_el_guitar_02", ["price"] = 100, ["name"] = "E Guitar 2" },
  [5] = { ["object"] = "prop_el_guitar_03", ["price"] = 100, ["name"] = "E Guitar 2" },
  [6] = { ["object"] = "prop_feed_sack_01", ["price"] = 100, ["name"] = "Feed Sack" },
  [7] = { ["object"] = "prop_floor_duster_01", ["price"] = 100, ["name"] = "Floor Duster" },
  [8] = { ["object"] = "prop_fruit_basket", ["price"] = 100, ["name"] = "Fruit Basket" },
  [9] = { ["object"] = "prop_f_duster_02", ["price"] = 100, ["name"] = "Duster" },
  [10] = { ["object"] = "prop_grapes_02", ["price"] = 100, ["name"] = "Grapes" },
  [11] = { ["object"] = "prop_hotel_clock_01", ["price"] = 100, ["name"] = "Hotel Clock" },
  [12] = { ["object"] = "prop_idol_case_01", ["price"] = 100, ["name"] = "Idol Case" },
  [13] = { ["object"] = "prop_jewel_02a", ["price"] = 100, ["name"] = "Jewels" },
  [14] = { ["object"] = "prop_jewel_02b", ["price"] = 100, ["name"] = "Jewels" },
  [15] = { ["object"] = "prop_jewel_02c", ["price"] = 100, ["name"] = "Jewels" },
  [16] = { ["object"] = "prop_jewel_03a", ["price"] = 100, ["name"] = "Jewels" },
  [17] = { ["object"] = "prop_jewel_03b", ["price"] = 100, ["name"] = "Jewels" },
  [18] = { ["object"] = "prop_jewel_04a", ["price"] = 100, ["name"] = "Jewels" },
  [19] = { ["object"] = "prop_jewel_04b", ["price"] = 100, ["name"] = "Jewels" },
  [20] = { ["object"] = "prop_j_disptray_01", ["price"] = 100, ["name"] = "Display Tray" },
  [21] = { ["object"] = "prop_j_disptray_01b", ["price"] = 100, ["name"] = "Display Tray" },
  [22] = { ["object"] = "prop_j_disptray_02", ["price"] = 100, ["name"] = "Display Tray" },
  [23] = { ["object"] = "prop_j_disptray_03", ["price"] = 100, ["name"] = "Display Tray" },
  [24] = { ["object"] = "prop_j_disptray_04", ["price"] = 100, ["name"] = "Display Tray" },
  [25] = { ["object"] = "prop_j_disptray_04b", ["price"] = 100, ["name"] = "Display Tray" },
  [26] = { ["object"] = "prop_j_disptray_05", ["price"] = 100, ["name"] = "Display Tray" },
  [27] = { ["object"] = "prop_j_disptray_05b", ["price"] = 100, ["name"] = "Display Tray" },
  [28] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 100, ["name"] = "Green Screen" },
  [29] = { ["object"] = "prop_ld_handbag", ["price"] = 100, ["name"] = "Handbag" },
  [30] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 100, ["name"] = "Jerry Can" },
  [31] = { ["object"] = "prop_ld_keypad_01", ["price"] = 100, ["name"] = "Keypad 1" },
  [32] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 100, ["name"] = "Keypad 2" },
  [33] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 100, ["name"] = "Suitcase 1" },
  [34] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 100, ["name"] = "Suitcase 2" },
  [35] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["name"] = "Suitcase 3"},
  [36] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 100, ["name"] = "Rasberry Clean" },
  [37] = { ["object"] = "prop_paper_bag_01", ["price"] = 100, ["name"] = "Paper Bag" },
  [38] = { ["object"] = "prop_shopping_bags01", ["price"] = 100, ["name"] = "Shopping Bags" },
  [39] = { ["object"] = "prop_shopping_bags02", ["price"] = 100, ["name"] = "Shopping Bags 2" },
  [40] = { ["object"] = "prop_yoga_mat_01", ["price"] = 100, ["name"] = "Yoga Mat 1" },
  [41] = { ["object"] = "prop_yoga_mat_02", ["price"] = 100, ["name"] = "Yoga Mat 2" },
  [42] = { ["object"] = "prop_yoga_mat_03", ["price"] = 100, ["name"] = "Yoga Mat 3" },
  [43] = { ["object"] = "p_ld_sax", ["price"] = 100, ["name"] = "Sax" },
  [44] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 100, ["name"] = "SOCCER Ball" },
  [45] = { ["object"] = "p_watch_01", ["price"] = 100, ["name"] = "Watch 1" },
  [46] = { ["object"] = "p_watch_02", ["price"] = 100, ["name"] = "Watch 2" },
  [47] = { ["object"] = "p_watch_03", ["price"] = 100, ["name"] = "Watch 3" },
  [48] = { ["object"] = "p_watch_04", ["price"] = 100, ["name"] = "Watch 4" },
  [49] = { ["object"] = "p_watch_05", ["price"] = 100, ["name"] = "Watch 5" },
  [51] = { ["object"] = "p_watch_06", ["price"] = 100, ["name"] = "Watch 6" },
  [52] = { ["object"] = "prop_suitcase_01", ["price"] = 100, ["name"] = "Suitcase 4" },
  [53] = { ["object"] = "prop_suitcase_01b", ["price"] = 100, ["name"] = "Suitcase 5" },
  [54] = { ["object"] = "prop_suitcase_01c", ["price"] = 100, ["name"] = "Suitcase 6" },
  [55] = { ["object"] = "prop_suitcase_01d", ["price"] = 100, ["name"] = "Suitcase 7" },
  [56] = { ["object"] = "prop_suitcase_02", ["price"] = 100, ["name"] = "Suitcase 8" },
  [57] = { ["object"] = "prop_suitcase_03", ["price"] = 100, ["name"] = "Suitcase 9" },
  [58] = { ["object"] = "prop_suitcase_03b", ["price"] = 100, ["name"] = "Suitcase 10" },
  [59] = { ["object"] = "ch_prop_ch_case_01a", ["price"] = 100, ["name"] = "Suitcase 11" },
  [60] = { ["object"] = "bkr_prop_biker_case_shut", ["price"] = 100, ["name"] = "Suitcase 12" },
  [61] = { ["object"] = "ch_prop_ch_security_case_01a", ["price"] = 100, ["name"] = "Suitcase 13" },
  [62] = { ["object"] = "ch_prop_ch_security_case_02a", ["price"] = 100, ["name"] = "Suitcase 14" },
  [63] = { ["object"] = "hei_prop_heist_trevor_case", ["price"] = 100, ["name"] = "Suitcase 15" },
  [64] = { ["object"] = "hei_prop_heist_thermite_case", ["price"] = 100, ["name"] = "Suitcase 16" },
  [65] = { ["object"] = "hei_prop_hei_drug_case", ["price"] = 100, ["name"] = "Suitcase 17" },
  [66] = { ["object"] = "hei_prop_hei_security_case", ["price"] = 100, ["name"] = "Suitcase 18" },
  [67] = { ["object"] = "hei_p_attache_case_01b_s", ["price"] = 100, ["name"] = "Suitcase 19" },
  [68] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 100, ["name"] = "Suitcase 20" },
},

["Small"] = {
  [1] = { ["object"] = "v_res_r_figcat", ["price"] = 300, ["name"] = "Fig Cat" },
  [2] = { ["object"] = "v_res_r_figclown", ["price"] = 300, ["name"] = "Fig Clown" },
  [3] = { ["object"] = "v_res_r_figauth2", ["price"] = 300, ["name"] = "Fig Auth" },
  [4] = { ["object"] = "v_res_r_figfemale", ["price"] = 300, ["name"] = "Fig Female" },
  [5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 300, ["name"] = "Fig Flamenco" },
  [6] = { ["object"] = "v_res_r_figgirl", ["price"] = 300, ["name"] = "Fig Girl" },
  [7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 300, ["name"] = "Fig Girl Clown" },
  [8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 300, ["name"] = "Fig Oblisk" },
  [9] = { ["object"] = "v_res_r_figpillar", ["price"] = 300, ["name"] = "Fig Pillar" },
  [10] = { ["object"] = "v_res_r_teapot", ["price"] = 300, ["name"] = "Teapot" },
  [11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 300, ["name"] = "Sculpture 1" },
  [12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 300, ["name"] = "Sculpture 2" },
  [13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 300, ["name"] = "Sculpture 3" },
  [14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 300, ["name"] = "Sculpture 4" },
  [15] = { ["object"] = "v_res_skateboard", ["price"] = 300, ["name"] = "Skateboard" },
  [16] = { ["object"] = "v_res_sketchpad", ["price"] = 300, ["name"] = "Sketchpad" },
  [17] = { ["object"] = "v_res_tissues", ["price"] = 300, ["name"] = "Tissues" },
  [18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 300, ["name"] = "Basket" },
  [19] = { ["object"] = "v_res_tre_bin", ["price"] = 300, ["name"] = "Bin" },
  [20] = { ["object"] = "v_res_tre_cushiona", ["price"] = 300, ["name"] = "Cushion 1" },
  [21] = { ["object"] = "v_res_tre_cushionb", ["price"] = 300, ["name"] = "Cushion 2" },
  [22] = { ["object"] = "v_res_tre_cushionc", ["price"] = 300, ["name"] = "Cushion 3" },
  [23] = { ["object"] = "v_res_tre_cushiond", ["price"] = 300, ["name"] = "Cushion 4" },
  [24] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 300, ["name"] = "Cushion 5" },
  [25] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 300, ["name"] = "Cushion 6" },
  [26] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 300, ["name"] = "Fruitbowl" },
  [27] = { ["object"] = "v_med_p_sideboard", ["price"] = 300, ["name"] = "Sideboard" },
  [28] = { ["object"] = "prop_idol_01", ["price"] = 100, ["name"] = "Idol 1" },
  [29] = { ["object"] = "p_cs_cuffs_02_s", ["price"] = 100, ["name"] = "Cuffs" },
  [30] = { ["object"] = "prop_cs_dildo_01", ["price"] = 100, ["name"] = "Good vibes" },
  [31] = { ["object"] = "v_res_d_dildo_a", ["price"] = 100, ["name"] = "Good vibes 2" },
  [32] = { ["object"] = "v_res_d_dildo_b", ["price"] = 100, ["name"] = "Good vibes 3" },
  [33] = { ["object"] = "v_res_d_dildo_c", ["price"] = 100, ["name"] = "Good vibes 4" },
  [34] = { ["object"] = "v_res_d_lube", ["price"] = 100, ["name"] = "Lube" },
  [35] = { ["object"] = "v_ret_gc_trays", ["price"] = 100, ["name"] = "Desk tray" },
  [36] = { ["object"] = "v_res_filebox01", ["price"] = 100, ["name"] = "File box" },
  [37] = { ["object"] = "ba_prop_club_champset", ["price"] = 100, ["name"] = "Champset" },
  [38] = { ["object"] = "ba_prop_club_water_bottle", ["price"] = 100, ["name"] = "Water Bottle" },
  [39] = { ["object"] = "ba_prop_club_tonic_can", ["price"] = 100, ["name"] = "Sprunk Can" },
  [40] = { ["object"] = "ba_prop_club_tonic_bottle", ["price"] = 100, ["name"] = "Tonic Bottle" },
  [41] = { ["object"] = "prop_cs_plate_01", ["price"] = 100, ["name"] = "Plate 1" },
  [42] = { ["object"] = "prop_plate_01", ["price"] = 100, ["name"] = "Plate 2" },
  [43] = { ["object"] = "prop_plate_03", ["price"] = 100, ["name"] = "Plate 3" },
  [44] = { ["object"] = "v_ilev_tt_plate01", ["price"] = 100, ["name"] = "Plate 4" },
  [45] = { ["object"] = "v_res_mplatelrg", ["price"] = 100, ["name"] = "Plate 5" },
  [46] = { ["object"] = "v_res_mplatesml", ["price"] = 100, ["name"] = "Plate 6" },
  [47] = { ["object"] = "v_res_tt_pizzaplate", ["price"] = 100, ["name"] = "Plate 7" },
  [48] = { ["object"] = "v_res_tt_platepile", ["price"] = 100, ["name"] = "Plate 8" },
  [49] = { ["object"] = "v_ret_fh_plate2", ["price"] = 100, ["name"] = "Plate 9" },
  [50] = { ["object"] = "v_ret_fh_plate3", ["price"] = 100, ["name"] = "Plate 10" },
  [51] = { ["object"] = "v_ret_fh_plate4", ["price"] = 100, ["name"] = "Plate 11" },
  [52] = { ["object"] = "apa_mp_h_acc_drink_tray_02", ["price"] = 100, ["name"] = "Drink Tray" },
  [53] = { ["object"] = "xs_prop_arena_cash_pile_l", ["price"] = 100, ["name"] = "Cash Pile" },
  [54] = { ["object"] = "bkr_prop_weed_dry_01a", ["price"] = 100, ["name"] = "Dry Weed 1" },
  [55] = { ["object"] = "bkr_prop_weed_dry_02a", ["price"] = 100, ["name"] = "Dry Weed 2" },
  [56] = { ["object"] = "bkr_prop_weed_dry_02b", ["price"] = 100, ["name"] = "Dry Weed 3" },
  [57] = { ["object"] = "bkr_prop_weed_lrg_01a", ["price"] = 100, ["name"] = "Weed 1" },
  [58] = { ["object"] = "bkr_prop_weed_lrg_01b", ["price"] = 100, ["name"] = "Weed 2" },
  [59] = { ["object"] = "bkr_prop_weed_med_01a", ["price"] = 100, ["name"] = "Weed 3" },
  [60] = { ["object"] = "bkr_prop_weed_med_01b", ["price"] = 100, ["name"] = "Weed 4" },
  [61] = { ["object"] = "ch_prop_gold_bar_01a", ["price"] = 100, ["name"] = "Gold Bar 1" },
  [62] = { ["object"] = "ex_prop_exec_award_gold", ["price"] = 1000, ["name"] = "Gold Award 1" },
  [63] = { ["object"] = "vw_prop_vw_pogo_gold_01a", ["price"] = 1000, ["name"] = "Golden Iman ?" },
  [64] = { ["object"] = "xs_prop_trophy_goldbag_01a", ["price"] = 1000, ["name"] = "Golden Trophy 2" },
  [65] = { ["object"] = "vw_prop_casino_art_basketball_02a", ["price"] = 1000, ["name"] = "Basketball Ball" },
  [66] = { ["object"] = "hei_heist_str_sideboardl_02", ["price"] = 300, ["name"] = "Sideboard 2" },
},


["Storage"] = {
  [1] = { ["object"] = "v_res_cabinet", ["price"] = 2500, ["name"] = "Cabinet Large" },
  [2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 2500, ["name"] = "Dressing Table" },
  [3] = { ["object"] = "v_res_d_sideunit", ["price"] = 2500, ["name"] = "Side Unit 1" },
  [4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 2500, ["name"] = "Side Unit 2" },
  [5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 2500, ["name"] = "Side Unit 3" },
  [6] = { ["object"] = "v_res_mbbedtable", ["price"] = 2500, ["name"] = "Bed Unit" },
  [7] = { ["object"] = "v_res_j_tvstand", ["price"] = 2500, ["name"] = "Tv Unit" },
  [8] = { ["object"] = "v_res_mbdresser", ["price"] = 2500, ["name"] = "Dresser Unit" },
  [9] = { ["object"] = "v_res_mbottoman", ["price"] = 2500, ["name"] = "Bottoman Unit" },
  [10] = { ["object"] = "v_res_mconsolemod", ["price"] = 2500, ["name"] = "Console Unit" },
  [11] = { ["object"] = "v_res_mcupboard", ["price"] = 2500, ["name"] = "Cupboard Unit" },
  [12] = { ["object"] = "v_res_mdchest", ["price"] = 2500, ["name"] = "Chest Unit" },
  [13] = { ["object"] = "v_res_msoncabinet", ["price"] = 2500, ["name"] = "Mason Unit" },
  [14] = { ["object"] = "v_res_m_armoire", ["price"] = 2500, ["name"] = "Armoire Unit" },
  [15] = { ["object"] = "v_res_m_sidetable", ["price"] = 2500, ["name"] = "Side Unit 4" },
  [16] = { ["object"] = "v_res_son_desk", ["price"] = 2500, ["name"] = "Desk Unit" },
  [17] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 2500, ["name"] = "Side Unit 5" },
  [18] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 2500, ["name"] = "Side Unit 6" },
  [19] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 2500, ["name"] = "Book Unit" },
  [20] = { ["object"] = "v_res_tre_storagebox", ["price"] = 2500, ["name"] = "Box Unit" },
  [21] = { ["object"] = "v_res_tre_storageunit", ["price"] = 2500, ["name"] = "Storage Unit" },
  [22] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 2500, ["name"] = "Wardrobe Unit" },
  [23] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 2500, ["name"] = "Wood Unit" },
  [24] = { ["object"] = "prop_devin_box_closed", ["price"] = 100, ["name"] = "Bean Bag 1" },
  [25] = { ["object"] = "prop_mil_crate_01", ["price"] = 100, ["name"] = "Mil Crate 1" },
  [26] = { ["object"] = "prop_mil_crate_02", ["price"] = 100, ["name"] = "Mil Crate 2" },
  [27] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 1100, ["name"] = "Safe" },
  [28] = { ["object"] = "apa_mp_h_bed_chestdrawer_02", ["price"] = 1100, ["name"] = "Drawer" },
  [29] = { ["object"] = "hei_heist_bed_chestdrawer_04", ["price"] = 1100, ["name"] = "Drawer" },
  [30] = { ["object"] = "ba_prop_battle_case_sm_03", ["price"] = 1100, ["name"] = "Case 1" },
  [31] = { ["object"] = "ba_prop_battle_vinyl_case", ["price"] = 1100, ["name"] = "Case 2" },
  [32] = { ["object"] = "bkr_prop_gunlocker_01a", ["price"] = 1100, ["name"] = "Gun Locker 1" },
  [33] = { ["object"] = "bkr_prop_gunlocker_01a", ["price"] = 1100, ["name"] = "Side Unit 7" },
  [34] = { ["object"] = "ch_prop_gold_trolly_01a", ["price"] = 1100, ["name"] = "Gold Trolly 1" },
  [35] = { ["object"] = "ch_prop_gold_trolly_01b", ["price"] = 1100, ["name"] = "Gold Trolly 2" },
  [36] = { ["object"] = "ch_prop_gold_trolly_01c", ["price"] = 1100, ["name"] = "Gold Trolly 3" },
  [37] = { ["object"] = "hei_prop_gold_trolly_empty", ["price"] = 10000, ["name"] = "Empty Gold Trolly" },
  [38] = { ["object"] = "hei_prop_gold_trolly_half_full", ["price"] = 50000, ["name"] = "Half Full Gold Trolly" },
  [39] = { ["object"] = "prop_gold_trolly_full", ["price"] = 100000, ["name"] = "Full Gold Trolly" },
  [40] = { ["object"] = "v_ilev_gold", ["price"] = 1000000, ["name"] = "Gold 1" },

},

["Electronics"] = {
  [1] = { ["object"] = "prop_trailr_fridge", ["price"] = 300, ["name"] = "Old Fridge" },
  [2] = { ["object"] = "v_res_fh_speaker", ["price"] = 300, ["name"] = "Speaker" },
  [3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 300, ["name"] = "Speaker Dock" },
  [4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 300, ["name"] = "Bedside Clock" },
  [5] = { ["object"] = "v_res_fa_phone", ["price"] = 300, ["name"] = "Phone 1" },
  [6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 300, ["name"] = "Tower Fan" },
  [7] = { ["object"] = "v_res_fa_fan", ["price"] = 300, ["name"] = "Fan" },
  [8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 300, ["name"] = "Bigscreen" },
  [9] = { ["object"] = "v_res_lest_monitor", ["price"] = 300, ["name"] = "Monitor" },
  [10] = { ["object"] = "v_res_tre_mixer", ["price"] = 300, ["name"] = "Mixer" },
  [11] = { ["object"] = "prop_cs_cctv", ["price"] = 100, ["name"] = "CCTV" },
  [12] = { ["object"] = "prop_ld_lap_top", ["price"] = 1000, ["name"] = "Laptop" },
  [13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 100, ["name"] = "Monitor 1" },
  [14] = { ["object"] = "xm_prop_x17_tv_flat_02", ["price"] = 500, ["name"] = "Flatscreen TV" },
  [15] = { ["object"] = "apa_mp_h_str_avunitm_03", ["price"] = 1000, ["name"] = "TV set 1" },
  [16] = { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 1000, ["name"] = "TV set 2" },
  [17] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 1000, ["name"] = "TV set 3" },
  [18] = { ["object"] = "bkr_prop_clubhouse_jukebox_02a", ["price"] = 1000, ["name"] = "Jukebox" },
  [19] = { ["object"] = "bkr_prop_weed_fan_floor_01a", ["price"] = 300, ["name"] = "Floor fan" },
  [20] = { ["object"] = "prop_cs_keyboard_01", ["price"] = 300, ["name"] = "Computer Keyboard" },
  [21] = { ["object"] = "ex_mp_h_acc_coffeemachine_01", ["price"] = 500, ["name"] = "Coffeemachine" },
  [22] = { ["object"] = "apa_mp_h_str_avunitm_01", ["price"] = 1000, ["name"] = "TV set 4" },
  [23] = { ["object"] = "apa_mp_h_str_avunitl_01_b", ["price"] = 1000, ["name"] = "TV set 5" },
  [24] = { ["object"] = "apa_mp_h_str_avunitl_04", ["price"] = 1000, ["name"] = "TV set 6" },
  [25] = { ["object"] = "hei_heist_str_avunitl_01", ["price"] = 1000, ["name"] = "TV set 7" },
  [26] = { ["object"] = "hei_heist_str_avunitl_03", ["price"] = 1000, ["name"] = "TV set 8" },
  [27] = { ["object"] = "hei_prop_dlc_tablet", ["price"] = 1000, ["name"] = "Tablet" },
  [28] = { ["object"] = "imp_prop_impexp_tablet", ["price"] = 1000, ["name"] = "Tablet 2" },
  [29] = { ["object"] = "prop_portable_hifi_01", ["price"] = 1000, ["name"] = "Hifi" },
  [30] = { ["object"] = "prop_table_mic_01", ["price"] = 1000, ["name"] = "Microphone" },
  [31] = { ["object"] = "ba_prop_battle_club_speaker_dj", ["price"] = 1000, ["name"] = "Speaker 1" },
  [32] = { ["object"] = "ba_prop_battle_club_speaker_large", ["price"] = 1000, ["name"] = "Speaker 2" },
  [33] = { ["object"] = "ba_prop_battle_club_speaker_array", ["price"] = 1000, ["name"] = "Speaker 3" },
  [34] = { ["object"] = "ba_prop_battle_club_speaker_med", ["price"] = 1000, ["name"] = "Speaker 4" },
  [35] = { ["object"] = "ba_prop_battle_club_speaker_small", ["price"] = 1000, ["name"] = "Speaker 5" },
  [36] = { ["object"] = "ba_prop_battle_dj_kit_speaker", ["price"] = 1000, ["name"] = "Speaker 6" },
  [37] = { ["object"] = "prop_speaker_01", ["price"] = 1000, ["name"] = "Speaker 7" },
  [38] = { ["object"] = "prop_speaker_02", ["price"] = 1000, ["name"] = "Speaker 8" },
  [39] = { ["object"] = "prop_speaker_03", ["price"] = 1000, ["name"] = "Speaker 9" },
  [40] = { ["object"] = "prop_speaker_05", ["price"] = 1000, ["name"] = "Speaker 10" },
  [41] = { ["object"] = "prop_speaker_07", ["price"] = 1000, ["name"] = "Speaker 11" },
  [42] = { ["object"] = "prop_speaker_08", ["price"] = 1000, ["name"] = "Speaker 12" },
  [43] = { ["object"] = "stt_prop_speakerstack_01a", ["price"] = 1000, ["name"] = "Speaker 13" },
  [44] = { ["object"] = "v_res_pcspeaker", ["price"] = 1000, ["name"] = "Speaker 14" },
  [45] = { ["object"] = "v_res_monitorwidelarge", ["price"] = 100, ["name"] = "Monitor 2" },
  [46] = { ["object"] = "v_res_monitor", ["price"] = 100, ["name"] = "Monitor 3" },
  [47] = { ["object"] = "vw_prop_vw_trailer_monitor_01", ["price"] = 100, ["name"] = "Monitor 4" },
  [48] = { ["object"] = "sm_prop_smug_monitor_01", ["price"] = 100, ["name"] = "Monitor 5" },
  [49] = { ["object"] = "prop_monitor_w_large", ["price"] = 100, ["name"] = "Monitor 6" },
  [50] = { ["object"] = "prop_monitor_04a", ["price"] = 100, ["name"] = "Monitor 7" },
  [51] = { ["object"] = "prop_mouse_01", ["price"] = 1000, ["name"] = "Mouse 1" },
  [52] = { ["object"] = "prop_mouse_02", ["price"] = 1000, ["name"] = "Mouse 2" },
  [53] = { ["object"] = "xm_prop_x17_laptop_agent14_01", ["price"] = 1000, ["name"] = "Laptop 2" },	
  [54] = { ["object"] = "prop_laptop_02_closed", ["price"] = 1000, ["name"] = "Laptop 3" },	
  [55] = { ["object"] = "prop_laptop_01a", ["price"] = 1000, ["name"] = "Laptop 4" },	
  [56] = { ["object"] = "xm_prop_x17_laptop_lester_01", ["price"] = 1000, ["name"] = "Laptop 5" },	
  [57] = { ["object"] = "ba_prop_club_laptop_dj", ["price"] = 1000, ["name"] = "Laptop 6" },	
  [58] = { ["object"] = "prop_fan_01", ["price"] = 1000, ["name"] = "Fan" },
  [59] = { ["object"] = "ba_prop_battle_dj_deck_01a", ["price"] = 1000, ["name"] = "Dj Deck 1" },
  [60] = { ["object"] = "ba_prop_battle_dj_kit_mixer", ["price"] = 1000, ["name"] = "Dj Kit Mixer" },
  [61] = { ["object"] = "ba_prop_battle_dj_kit_mixer", ["price"] = 1000, ["name"] = "Dj Kit Speaker" },
  [62] = { ["object"] = "ba_prop_battle_dj_mixer_01a", ["price"] = 1000, ["name"] = "Dj Mixer 1" },
  [63] = { ["object"] = "ba_prop_battle_dj_mixer_01b", ["price"] = 1000, ["name"] = "Dj Mixer 2" },
  [64] = { ["object"] = "ba_prop_battle_dj_mixer_01c", ["price"] = 1000, ["name"] = "Dj Mixer 3" },
  [65] = { ["object"] = "ba_prop_battle_dj_mixer_01d", ["price"] = 1000, ["name"] = "Dj Mixer 4" },
  [66] = { ["object"] = "ba_prop_battle_dj_mixer_01e", ["price"] = 1000, ["name"] = "Dj Mixer 5" },
  [67] = { ["object"] = "ba_prop_battle_dj_stand", ["price"] = 1000, ["name"] = "Dj Stand" },
  [68] = { ["object"] = "ba_prop_battle_headphones_dj", ["price"] = 1000, ["name"] = "Dj Headphone" },
  [69] = { ["object"] = "prop_dj_deck_01", ["price"] = 1000, ["name"] = "Dj Deck 2" },
  [70] = { ["object"] = "prop_dj_deck_02", ["price"] = 1000, ["name"] = "Dj Deck 3" },
  [71] = { ["object"] = "v_ret_ta_camera", ["price"] = 100, ["name"] = "Cam 1" },
  [73] = { ["object"] = "prop_film_cam_01", ["price"] = 100, ["name"] = "Cam 3" },
  [74] = { ["object"] = "prop_ing_camera_01", ["price"] = 100, ["name"] = "Cam 4" },
  [75] = { ["object"] = "prop_pap_camera_01", ["price"] = 100, ["name"] = "Cam 5" },
  [76] = { ["object"] = "prop_spycam", ["price"] = 100, ["name"] = "Cam 6" },
  [77] = { ["object"] = "prop_tv_cam_02", ["price"] = 100, ["name"] = "Cam 7" },
  [78] = { ["object"] = "prop_v_cam_01", ["price"] = 100, ["name"] = "Cam 8" },
  [79] = { ["object"] = "ba_prop_battle_club_screen_02", ["price"] = 100, ["name"] = "Monitor 8" },
  [80] = { ["object"] = "ba_prop_battle_club_screen_03", ["price"] = 100, ["name"] = "Monitor 9" },
  [81] = { ["object"] = "v_club_roc_micstd", ["price"] = 100, ["name"] = "Mic Stand 1" },
  [82] = { ["object"] = "apa_mp_h_acc_phone_01", ["price"] = 100, ["name"] = "Phone 2" },
  [83] = { ["object"] = "hei_prop_hei_bank_phone_01", ["price"] = 100, ["name"] = "Phone 3" },
  [84] = { ["object"] = "prop_office_phone_tnt", ["price"] = 100, ["name"] = "Phone 4" },
  [85] = { ["object"] = "prop_off_phone_01", ["price"] = 100, ["name"] = "Phone 5" },
  [86] = { ["object"] = "vw_prop_casino_phone_01a", ["price"] = 100, ["name"] = "Phone 6" },
},


["Lighting"] = {
  [1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 100, ["name"] = "Desk Corp Lamp" },
  [2] = { ["object"] = "v_res_desklamp", ["price"] = 100, ["name"] = "Desk Lamp" },
  [3] = { ["object"] = "v_res_d_lampa", ["price"] = 100, ["name"] = "Lamp AA" },
  [4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 100, ["name"] = "Lamp 1" },
  [5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 100, ["name"] = "Floor Lamp" },
  [6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 100, ["name"] = "Lamp 2" },
  [7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 100, ["name"] = "Table Lamp" },
  [8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 100, ["name"] = "Table Lamp 2" },
  [9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 100, ["name"] = "Bed Lamp" },
  [10] = { ["object"] = "v_res_mplanttongue", ["price"] = 100, ["name"] = "Plant Tongue Lamp" },
  [11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 100, ["name"] = "Table Lamp 3" },
  [12] = { ["object"] = "v_res_m_lampstand", ["price"] = 100, ["name"] = "Lamp Stand" },
  [13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 100, ["name"] = "Lamp Stand 2" },
  [14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 100, ["name"] = "Table Lamp 4" },
  [15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 100, ["name"] = "Light Fan" },
  [16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 100, ["name"] = "Tall Lamp" },
  [17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 100, ["name"] = "Wall Light" },
  [18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 100, ["name"] = "GC Lamp" },
  [19] = { ["object"] = "prop_dummy_light", ["price"] = 100, ["name"] = "Flickering Light" },
  [20] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 100, ["name"] = "Side Wall Light 1" },
  [21] = { ["object"] = "V_44_D_emis", ["price"] = 100, ["name"] = "Test Light" },
  [22] = { ["object"] = "hei_heist_wall_light003", ["price"] = 2000, ["name"] = "Ceiling Light" },
  [23] = { ["object"] = "apa_mp_h_lit_lamptablenight_16", ["price"] = 100, ["name"] = "Table Lamp 3" },
  [24] = { ["object"] = "apa_mp_h_lit_lightpendant_01", ["price"] = 100, ["name"] = "Light 1" },
  [25] = { ["object"] = "apa_mp_h_lit_lightpendant_05", ["price"] = 100, ["name"] = "Light 2" },
  [26] = { ["object"] = "apa_mp_h_lit_lightpendant_05b", ["price"] = 100, ["name"] = "Light 3" },
  [27] = { ["object"] = "ba_prop_battle_lights_ceiling_l_a", ["price"] = 100, ["name"] = "Light 4" },
  [28] = { ["object"] = "ba_prop_battle_lights_ceiling_l_b", ["price"] = 100, ["name"] = "Light 5" },
  [29] = { ["object"] = "ba_prop_battle_lights_ceiling_l_c", ["price"] = 100, ["name"] = "Light 6" },
  [30] = { ["object"] = "ba_prop_battle_lights_ceiling_l_f", ["price"] = 100, ["name"] = "Light 7" },
  [31] = { ["object"] = "ba_prop_battle_lights_ceiling_l_f", ["price"] = 100, ["name"] = "Light 8" },
  [32] = { ["object"] = "ba_prop_battle_lights_tube_l_a", ["price"] = 100, ["name"] = "Wall Light 2" },
  [33] = { ["object"] = "ba_prop_battle_lights_tube_l_b", ["price"] = 100, ["name"] = "Wall Light 3" },
  [34] = { ["object"] = "ba_prop_battle_lights_wall_l_b", ["price"] = 100, ["name"] = "Wall Light 4" },
  [35] = { ["object"] = "ba_prop_battle_lights_wall_l_c", ["price"] = 100, ["name"] = "Wall Light 5" },
  [36] = { ["object"] = "apa_mp_h_lampbulb_multiple_a", ["price"] = 100, ["name"] = "Light 9" },
  [37] = { ["object"] = "apa_mp_h_lit_floorlamp_13", ["price"] = 100, ["name"] = "Floor Lamp 1" },
  [38] = { ["object"] = "apa_mp_h_lit_floorlamp_10", ["price"] = 100, ["name"] = "Floor Lamp 2" },
  [39] = { ["object"] = "vw_prop_casino_art_lampf_01a", ["price"] = 100, ["name"] = "Casino Art Lamp 1" },
  [40] = { ["object"] = "vw_prop_casino_art_lampm_01a", ["price"] = 100, ["name"] = "Casino Art Lamp 2" },
  [41] = { ["object"] = "hei_heist_lit_lamptable_06", ["price"] = 100, ["name"] = "Table Lamp 4" },
  [42] = { ["object"] = "prop_wall_light_02a", ["price"] = 100, ["name"] = "Wall Light 6" },
  [43] = { ["object"] = "prop_wall_light_13a", ["price"] = 100, ["name"] = "Wall Light 7" },
  [44] = { ["object"] = "prop_walllight_ld_01", ["price"] = 100, ["name"] = "Wall Light 8" },
  [45] = { ["object"] = "prop_walllight_ld_01b", ["price"] = 100, ["name"] = "Wall Light 9" },
  [46] = { ["object"] = "prop_wall_light_02a", ["price"] = 100, ["name"] = "Wall Light 10" },
  [47] = { ["object"] = "prop_wall_light_05a", ["price"] = 100, ["name"] = "Wall Light 11" },

},


["Tables"] = {
  [1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 500, ["name"] = "Coffee Table 1" },
  [2] = { ["object"] = "v_res_d_roundtable", ["price"] = 500, ["name"] = "Round Table" },
  [3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 500, ["name"] = "Small Side Table" },
  [4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 500, ["name"] = "Table A" },
  [5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 500, ["name"] = "Table B" },
  [6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 500, ["name"] = "Table C" },
  [7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 500, ["name"] = "Dining Table" },
  [8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 500, ["name"] = "Coffee Table 2" },
  [9] = { ["object"] = "v_res_j_lowtable", ["price"] = 500, ["name"] = "Low Table" },
  [10] = { ["object"] = "v_res_mdbedtable", ["price"] = 500, ["name"] = "Bed Table" },
  [11] = { ["object"] = "v_res_mddesk", ["price"] = 500, ["name"] = "Desk" },
  [12] = { ["object"] = "v_res_msidetblemod", ["price"] = 500, ["name"] = "Side Table" },
  [13] = { ["object"] = "v_res_m_console", ["price"] = 500, ["name"] = "Console Table" },
  [14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 500, ["name"] = "Dining Table 2" },
  [15] = { ["object"] = "v_res_m_h_console", ["price"] = 500, ["name"] = "Console H Table" },
  [16] = { ["object"] = "v_res_m_stool", ["price"] = 500, ["name"] = "Stool?" },
  [17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 500, ["name"] = "Sideboard Table" },
  [18] = { ["object"] = "v_res_tre_table2", ["price"] = 500, ["name"] = "Table 2" },
  [19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 500, ["name"] = "Tv Table" },
  [20] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 500, ["name"] = "Tv Table Tall" },
  [21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 500, ["name"] = "Med Coffee Table" },
  [22] = { ["object"] = "v_med_p_desk", ["price"] = 500, ["name"] = "Med Desk" },
  [23] = { ["object"] = "prop_yacht_table_01", ["price"] = 100, ["name"] = "Yacht Table 1" },
  [24] = { ["object"] = "prop_yacht_table_02", ["price"] = 100, ["name"] = "Yacht Table 2" },
  [25] = { ["object"] = "prop_yacht_table_03", ["price"] = 100, ["name"] = "Yacht Table 3" },
  [26] = { ["object"] = "v_ret_csr_table", ["price"] = 100, ["name"] = "CSR Table" },
  [27] = { ["object"] = "hei_heist_din_table_06", ["price"] = 100, ["name"] = "Dinner table w chairs" },
  [28] = { ["object"] = "apa_mp_h_din_table_04", ["price"] = 100, ["name"] = "Dining Table 2" },
  [29] = { ["object"] = "apa_mp_h_din_table_05", ["price"] = 100, ["name"] = "Dining Table 3" },
  [30] = { ["object"] = "apa_mp_h_yacht_coffee_table_01", ["price"] = 100, ["name"] = "Yacht Table 4" },
  [31] = { ["object"] = "apa_mp_h_yacht_coffee_table_02", ["price"] = 100, ["name"] = "Yacht Table 5" },
  [32] = { ["object"] = "ba_prop_int_edgy_table_01", ["price"] = 100, ["name"] = "Table 1" },
  [33] = { ["object"] = "ba_prop_int_edgy_table_02", ["price"] = 100, ["name"] = "Table 2" },
  [34] = { ["object"] = "ba_prop_int_glam_table", ["price"] = 100, ["name"] = "Table 3" },
  [35] = { ["object"] = "ch_prop_ch_coffe_table_02", ["price"] = 100, ["name"] = "Table 4" },
  [36] = { ["object"] = "hei_heist_din_table_01", ["price"] = 100, ["name"] = "Table 5" },
  [37] = { ["object"] = "hei_heist_din_table_04", ["price"] = 100, ["name"] = "Table 6" },
  [38] = { ["object"] = "hei_heist_din_table_07", ["price"] = 100, ["name"] = "Table 7" },
  [39] = { ["object"] = "prop_chateau_table_01", ["price"] = 100, ["name"] = "Table 8" },
  [40] = { ["object"] = "prop_fbi3_coffee_table", ["price"] = 100, ["name"] = "Table 9" },
  [41] = { ["object"] = "prop_ld_farm_table01", ["price"] = 100, ["name"] = "Table 10" },
  [42] = { ["object"] = "prop_pooltable_02", ["price"] = 100, ["name"] = "Pool Table" },
  [43] = { ["object"] = "prop_pooltable_3b", ["price"] = 100, ["name"] = "Pool Table 2" },
  [44] = { ["object"] = "prop_table_03", ["price"] = 100, ["name"] = "Plastic Table" },	
  [44] = { ["object"] = "prop_table_03b", ["price"] = 100, ["name"] = "Plastic Table 2" },	
  [45] = { ["object"] = "prop_table_06", ["price"] = 100, ["name"] = "Table 11" },
  [46] = { ["object"] = "prop_table_07", ["price"] = 100, ["name"] = "Table 12" },
  [47] = { ["object"] = "prop_table_tennis", ["price"] = 100, ["name"] = "Tennis Table" },
  [48] = { ["object"] = "xm_base_cia_desk1", ["price"] = 100, ["name"] = "Desk Table" },
  [49] = { ["object"] = "ch_prop_table_casino_short_02a", ["price"] = 100, ["name"] = "Casino Table 1" },
  [50] = { ["object"] = "ch_prop_table_casino_tall_01a", ["price"] = 100, ["name"] = "Casino Table 2" },
  [51] = { ["object"] = "xm_base_cia_data_desks", ["price"] = 20000, ["name"] = "Data Desks" },
  [52] = { ["object"] = "xm_prop_base_staff_desk_02", ["price"] = 5000, ["name"] = "Staff Desk" },

}, 

["Plants"] = {
  [1] = { ["object"] = "prop_fib_plant_01", ["price"] = 150, ["name"] = "Plant Fib" },
  [2] = { ["object"] = "v_corp_bombplant", ["price"] = 170, ["name"] = "Plant Bomb" },    
  [3] = { ["object"] = "v_res_mflowers", ["price"] = 170, ["name"] = "Plant Flowers" }, 
  [4] = { ["object"] = "v_res_mvasechinese", ["price"] = 170, ["name"] = "Plant Chinese" }, 
  [5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 170, ["name"] = "Plant Banana" }, 
  [6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 170, ["name"] = "Plant Palm" },  
  [7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 170, ["name"] = "Plant Palm 2" },  
  [8] = { ["object"] = "v_res_m_urn", ["price"] = 170, ["name"] = "Plant Urn" },  
  [9] = { ["object"] = "v_res_rubberplant", ["price"] = 170, ["name"] = "Plant Rubber" }, 
  [10] = { ["object"] = "v_res_tre_plant", ["price"] = 170, ["name"] = "Plant" }, 
  [11] = { ["object"] = "v_res_tre_tree", ["price"] = 170, ["name"] = "Plant Tree" }, 
  [12] = { ["object"] = "v_med_p_planter", ["price"] = 170, ["name"] = "Planter" }, 
  [13] = { ["object"] = "v_ret_flowers", ["price"] = 100, ["name"] = "Flowers" },
  [14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 100, ["name"] = "Flowers 1" },
  [15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 100, ["name"] = "Flowers 2" },
  [16] = { ["object"] = "apa_mp_h_acc_vase_flowers_01", ["price"] = 100, ["name"] = "Flowers 3" },
  [17] = { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 100, ["name"] = "Flowers 4" },
  [18] = { ["object"] = "xm_prop_x17_xmas_tree_int", ["price"] = 500, ["name"] = "Christmas Tree" },
  [19] = { ["object"] = "apa_mp_h_acc_vase_flowers_03", ["price"] = 100, ["name"] = "Flowers 5" },
  [20] = { ["object"] = "apa_mp_h_acc_vase_flowers_04", ["price"] = 100, ["name"] = "Flowers 6" },
  [21] = { ["object"] = "hei_heist_acc_flowers_01", ["price"] = 100, ["name"] = "Flowers 7" },
  [22] = { ["object"] = "hei_heist_acc_flowers_02", ["price"] = 100, ["name"] = "Flowers 8" },
  [23] = { ["object"] = "vw_prop_flowers_potted_01a", ["price"] = 100, ["name"] = "Flowers 9" },
  [24] = { ["object"] = "vw_prop_flowers_potted_02a", ["price"] = 100, ["name"] = "Flowers 10" },
  [25] = { ["object"] = "vw_prop_flowers_vase_01a", ["price"] = 100, ["name"] = "Flowers 11" },
  [26] = { ["object"] = "p_int_jewel_plant_01", ["price"] = 100, ["name"] = "Flowers 12" },
  [27] = { ["object"] = "p_int_jewel_plant_02", ["price"] = 100, ["name"] = "Flowers 13" },
},

["Kitchen"] = {
  [1] = { ["object"] = "prop_washer_01", ["price"] = 150, ["name"] = "Washer 1" },
  [2] = { ["object"] = "prop_washer_02", ["price"] = 150, ["name"] = "Washer 2" },
  [3] = { ["object"] = "prop_washer_03", ["price"] = 150, ["name"] = "Washer 3" },
  [4] = { ["object"] = "prop_washing_basket_01", ["price"] = 150, ["name"] = "Washing Basket" },
  [5] = { ["object"] = "v_res_fridgemoda", ["price"] = 150, ["name"] = "Fridge 1" },
  [6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 150, ["name"] = "Fridge 2" },
  [7] = { ["object"] = "prop_fridge_01", ["price"] = 150, ["name"] = "Fridge 3" },
  [8] = { ["object"] = "prop_fridge_03", ["price"] = 150, ["name"] = "Fridge 4" },
  [9] = { ["object"] = "prop_cooker_03", ["price"] = 150, ["name"] = "Cooker" },
  [10] = { ["object"] = "prop_micro_01", ["price"] = 150, ["name"] = "Microwave 1" },
  [11] = { ["object"] = "prop_micro_02", ["price"] = 150, ["name"] = "Microwave 2" },
  [12] = { ["object"] = "prop_wok", ["price"] = 150, ["name"] = "Wok" },
  [13] = { ["object"] = "v_res_cakedome", ["price"] = 150, ["name"] = "Cake Plate" },
  [14] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 150, ["name"] = "Chopping Board" },
  [15] = { ["object"] = "v_res_mutensils", ["price"] = 150, ["name"] = "Utensils" },
  [16] = { ["object"] = "v_res_pestle", ["price"] = 150, ["name"] = "Pestle" },
  [17] = { ["object"] = "v_ret_ta_paproll", ["price"] = 150, ["name"] = "PaperRoll 1" },
  [18] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 150, ["name"] = "PaperRoll 2" },
  [19] = { ["object"] = "v_ret_fh_pot01", ["price"] = 150, ["name"] = "Pot 1" },
  [20] = { ["object"] = "v_ret_fh_pot02", ["price"] = 150, ["name"] = "Pot 2" },
  [21] = { ["object"] = "v_ret_fh_pot05", ["price"] = 150, ["name"] = "Pot 3" },
  [22] = { ["object"] = "prop_pot_03", ["price"] = 150, ["name"] = "Pot 4" },
  [23] = { ["object"] = "prop_pot_04", ["price"] = 150, ["name"] = "Pot 5" },
  [24] = { ["object"] = "prop_pot_05", ["price"] = 150, ["name"] = "Pot 6" },
  [25] = { ["object"] = "prop_pot_06", ["price"] = 150, ["name"] = "Pot 7" },
  [26] = { ["object"] = "prop_pot_rack", ["price"] = 150, ["name"] = "Pot Rack" },
  [27] = { ["object"] = "prop_kitch_juicer", ["price"] = 150, ["name"] = "Juicer" },
  [28] = { ["object"] = "ba_prop_battle_bar_beerfridge_01", ["price"] = 150, ["name"] = "Beer Fridge" },
  [29] = { ["object"] = "ba_prop_battle_bar_fridge_01", ["price"] = 150, ["name"] = "Bar Fridge 1" },
  [30] = { ["object"] = "ba_prop_battle_bar_fridge_02", ["price"] = 150, ["name"] = "Bar Fridge 2" },
  [31] = { ["object"] = "prop_bar_fridge_03", ["price"] = 150, ["name"] = "Fridge 3" },

},


["Bathroom"] = {
  [1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 100, ["name"] = "Toilet 1" },
  [2] = { ["object"] = "prop_toilet_01", ["price"] = 100, ["name"] = "Toilet 2" },
  [3] = { ["object"] = "prop_toilet_02", ["price"] = 100, ["name"] = "Toilet 3" },
  [4] = { ["object"] = "prop_sink_02", ["price"] = 100, ["name"] = "Sink 1" },
  [5] = { ["object"] = "prop_sink_04", ["price"] = 100, ["name"] = "Sink 2" },
  [6] = { ["object"] = "prop_sink_05", ["price"] = 100, ["name"] = "Sink 3" },
  [7] = { ["object"] = "prop_sink_06", ["price"] = 100, ["name"] = "Sink 4" },
  [8] = { ["object"] = "prop_soap_disp_01", ["price"] = 100, ["name"] = "Soap Dispenser" },
  [9] = { ["object"] = "prop_shower_rack_01", ["price"] = 100, ["name"] = "Shower Rack" },
  [10] = { ["object"] = "prop_handdry_01", ["price"] = 100, ["name"] = "Hand Dryer 1" },
  [11] = { ["object"] = "prop_handdry_02", ["price"] = 100, ["name"] = "Hand Dryer 2" },
  [12] = { ["object"] = "prop_towel_rail_01", ["price"] = 100, ["name"] = "Towel Rail 1" },
  [13] = { ["object"] = "prop_towel_rail_02", ["price"] = 100, ["name"] = "Towel Rail 2" },
  [14] = { ["object"] = "prop_towel_01", ["price"] = 100, ["name"] = "Towel 1" },
  [15] = { ["object"] = "v_res_mbtowel", ["price"] = 100, ["name"] = "Towel 2" },
  [16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 100, ["name"] = "Towel 3" },
  [17] = { ["object"] = "v_res_mbath", ["price"] = 100, ["name"] = "Bath 1" },
  [18] = { ["object"] = "v_res_mbsink", ["price"] = 100, ["name"] = "Sink" },
  [19] = { ["object"] = "apa_mp_h_bathtub_01", ["price"] = 100, ["name"] = "Bath 2" },

},

["Medical"] = {
  [1] = { ["object"] = "v_med_barrel", ["price"] = 750, ["name"] = "Barrel" },
  [2] = { ["object"] = "v_med_apecrate", ["price"] = 750, ["name"] = "Ape Crate" },
  [3] = { ["object"] = "v_med_apecratelrg", ["price"] = 750, ["name"] = "Ape Crate Large" },
  [4] = { ["object"] = "v_med_bed1", ["price"] = 750, ["name"] = "Bed 1" },
  [5] = { ["object"] = "v_med_bed2", ["price"] = 750, ["name"] = "Bed 2" },
  [6] = { ["object"] = "v_med_bedtable", ["price"] = 750, ["name"] = "Bed Table" },
  [7] = { ["object"] = "v_med_bench1", ["price"] = 750, ["name"] = "Bench 1" },
  [8] = { ["object"] = "v_med_bench2", ["price"] = 750, ["name"] = "Bench 2" },
  [9] = { ["object"] = "v_med_benchcentr", ["price"] = 750, ["name"] = "Bench Center" },
  [10] = { ["object"] = "v_med_benchset1", ["price"] = 750, ["name"] = "Bench Set" },
  [11] = { ["object"] = "v_med_bigtable", ["price"] = 750, ["name"] = "Big Table" },
  [12] = { ["object"] = "v_med_bin", ["price"] = 150, ["name"] = "Bin" },
  [13] = { ["object"] = "v_med_centrifuge1", ["price"] = 750, ["name"] = "Centrifuge" },
  [14] = { ["object"] = "v_med_cooler", ["price"] = 750, ["name"] = "Cooler" },
  [15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 750, ["name"] = "Monitor" },
  [16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 750, ["name"] = "Autopsy Table" },
  [17] = { ["object"] = "v_med_cor_cembin", ["price"] = 750, ["name"] = "Bin" },
  [18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 750, ["name"] = "Trolley" },
  [19] = { ["object"] = "v_med_cor_chemical", ["price"] = 750, ["name"] = "Chem" },
  [20] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 750, ["name"] = "BLM Table" },
  [21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 750, ["name"] = "File Box" },
  [22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 750, ["name"] = "File Cab" },
  [23] = { ["object"] = "v_med_cor_hose", ["price"] = 750, ["name"] = "Hose" },
  [24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 750, ["name"] = "Large Cupboard" },
  [25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 750, ["name"] = "Lightbox" },
  [26] = { ["object"] = "v_med_cor_medstool", ["price"] = 750, ["name"] = "Medstool" },
  [27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 750, ["name"] = "Minifridge" },
  [28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 750, ["name"] = "Papertowels" },
  [29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 750, ["name"] = "Photocopy" },
  [30] = { ["object"] = "v_med_cor_tvstand", ["price"] = 750, ["name"] = "TV Stand" },
  [31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 750, ["name"] = "Wall Unit" },
  [32] = { ["object"] = "v_med_examlight", ["price"] = 750, ["name"] = "Exam light" },
  [33] = { ["object"] = "v_med_gastank", ["price"] = 750, ["name"] = "Gas Tank" },
  [34] = { ["object"] = "v_med_hazmatscan", ["price"] = 750, ["name"] = "Hazmat Scan" },
  [35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 750, ["name"] = "Head Wall" },
  [36] = { ["object"] = "v_med_hospseating1", ["price"] = 750, ["name"] = "Seating" },
  [37] = { ["object"] = "v_med_hosptable", ["price"] = 750, ["name"] = "Hosp Table" },
  [38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 50, ["name"] = "Glove Box" },
  [39] = { ["object"] = "v_med_medwastebin", ["price"] = 750, ["name"] = "Wastebin" },
  [40] = { ["object"] = "v_med_oscillator3", ["price"] = 750, ["name"] = "Oscillator" },
  [41] = { ["object"] = "prop_ld_health_pack", ["price"] = 100, ["name"] = "Health Pack" },
}
}

lookuptable = {}
dropdowntable = {}
hashtable = {}

for category,v in pairs(furni.objects) do 
dropdowntable[category] = {}

for o,k in pairs(v) do

  local hash = GetHashKey(k.object)
  hashtable[hash] = k

  local id = k.object or "none"
  local name = k.name or "none"
  local price = k.price or 9999

  lookuptable[id] = k

  table.insert(dropdowntable[category],{id = id,name = name,price = price})
end 
end 

for k,v in pairs(furni.objects) do
for k,v in pairs(v) do
  v.id = v.object
end
end

if not Config.UsingNativeHousing then
TriggerEvent('esx:getSharedObject', function(obj) ESX = obj; end)
Citizen.CreateThread(function(...) while not ESX do TriggerEvent('esx:getSharedObject',function(obj) ESX = obj; end); Citizen.Wait(0); end; end)
end